export const CLOUD_TABLES = Object.freeze({tasks:'tasks',habits:'habits',habitEntries:'habit_entries',notes:'notes',folders:'note_folders',focusSessions:'focus_sessions',settings:'user_settings'});
export const CLOUD_SYNC_ORDER = Object.freeze(['tasks','habits','habitEntries','folders','notes','focusSessions','settings']);
const list=value=>Array.isArray(value)?value:[];
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const copy=value=>JSON.parse(JSON.stringify(value));
const time=value=>{if(typeof value==='number'&&Number.isFinite(value))return value;const parsed=Date.parse(value||'');return Number.isFinite(parsed)?parsed:0};
const iso=value=>new Date(Math.max(0,time(value)||Date.now())).toISOString();
const localTime=value=>time(value)||Date.now();
export const stableStringify=value=>Array.isArray(value)?`[${value.map(stableStringify).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`:JSON.stringify(value);
export const hasPlannerData=state=>['tasks','notes','habits','folders','focusSessions'].some(key=>list(state?.[key]).length>0);
export const settingsFor=state=>({challengeStart:state.challengeStart||'',challengeDays:Number(state.challengeDays)||0,challengeName:state.challengeName||'',onboarded:Boolean(state.onboarded),tourSeen:Boolean(state.tourSeen),taskMemory:list(state.taskMemory),reminders:obj(state.reminders),profile:obj(state.profile),stats:obj(state.stats),security:obj(state.security)});
export const protectedNoteInvariant=note=>!note?.protected||(note.title===''&&note.body===''&&Array.isArray(note.items)&&note.items.length===0&&note.kind==='protected'&&note.secure&&typeof note.secure==='object');
const itemTime=(item,state)=>iso(item?.updatedAt||item?.createdAt||state?._savedAt||Date.now());
export function collectionsFor(state){const safe=obj(state),entryTimes=obj(safe.syncMeta?.habitEntryUpdatedAt),tombstones=obj(safe.syncMeta?.tombstones),out={tasks:new Map(),habits:new Map(),habitEntries:new Map(),notes:new Map(),folders:new Map(),focusSessions:new Map(),settings:new Map()};list(safe.tasks).forEach(task=>out.tasks.set(task.id,{id:task.id,title:task.title||'',date:task.date||null,duration:task.duration??null,category:task.category||'Личное',priority:Boolean(task.priority),challenge:Boolean(task.challenge),completed:Boolean(task.completed),completedAt:task.completedAt||null,createdAt:task.createdAt||null,updatedAt:itemTime(task,safe)}));list(safe.habits).forEach(habit=>out.habits.set(habit.id,{id:habit.id,title:habit.title||'',createdAt:habit.createdAt||null,updatedAt:itemTime(habit,safe)}));Object.entries(obj(safe.checks)).forEach(([habitId,dates])=>list(dates).forEach(date=>{const id=`${habitId}:${date}`;out.habitEntries.set(id,{id,habitId,date,completed:true,updatedAt:iso(entryTimes[id]||safe._savedAt||Date.now())})}));list(safe.notes).forEach(note=>{if(!protectedNoteInvariant(note))throw new Error('Protected note invariant failed');out.notes.set(note.id,{id:note.id,folderId:note.folderId||'',title:note.protected?'':note.title||'',body:note.protected?'':note.body||'',kind:note.protected?'protected':note.kind||'text',items:note.protected?[]:list(note.items),done:Boolean(note.done),protected:Boolean(note.protected),secure:note.protected?obj(note.secure):null,createdAt:note.createdAt||null,updatedAt:itemTime(note,safe)});});list(safe.folders).forEach(folder=>out.folders.set(folder.id,{id:folder.id,name:folder.name||'',createdAt:folder.createdAt||null,updatedAt:itemTime(folder,safe)}));list(safe.focusSessions).forEach(session=>out.focusSessions.set(session.id,{id:session.id,taskId:session.taskId||null,durationMinutes:Number(session.durationMinutes)||0,startedAt:session.startedAt||null,completedAt:session.completedAt||null,status:session.status||'completed',createdAt:session.createdAt||null,updatedAt:itemTime(session,safe)}));out.settings.set('settings',{id:'settings',data:settingsFor(safe),updatedAt:iso(safe.syncMeta?.settingsUpdatedAt||safe._savedAt||Date.now())});Object.values(tombstones).forEach(record=>{if(!record?.collection||!out[record.collection]||!record.id)return;const active=out[record.collection].get(record.id);if(!active||time(record.deletedAt||record.updatedAt)>=time(active.updatedAt))out[record.collection].set(record.id,record)});return out}
const fingerprint=record=>{const next={...record};delete next.createdAt;delete next.updatedAt;return stableStringify(next)};
export function prepareState(state,previous=null,now=Date.now()){state.syncMeta=obj(state.syncMeta);state.syncMeta.habitEntryUpdatedAt=obj(state.syncMeta.habitEntryUpdatedAt);state.syncMeta.tombstones=obj(state.syncMeta.tombstones);state.syncMeta.seededAt||=now;const old=previous||collectionsFor(state),touch=(key,items)=>list(items).forEach(item=>{if(!item?.id)return;item.createdAt||=now;const earlier=old[key]?.get(item.id);if(!item.updatedAt||!earlier||fingerprint(earlier)!==fingerprint({...item,updatedAt:earlier.updatedAt}))item.updatedAt=now});touch('tasks',state.tasks);touch('habits',state.habits);touch('notes',state.notes);touch('folders',state.folders);touch('focusSessions',state.focusSessions);const raw=collectionsFor({...state,syncMeta:{...state.syncMeta,tombstones:{}}});Object.keys(CLOUD_TABLES).filter(collection=>collection!=='settings').forEach(collection=>old[collection]?.forEach((record,id)=>{if(!record.deletedAt&&!raw[collection].has(id))state.syncMeta.tombstones[`${collection}:${id}`]={...record,collection,id,deletedAt:iso(now),updatedAt:iso(now)}}));const next=collectionsFor(state);next.habitEntries.forEach((entry,id)=>{if(!state.syncMeta.habitEntryUpdatedAt[id]||(old.habitEntries?.has(id)&&fingerprint(old.habitEntries.get(id))!==fingerprint(entry)))state.syncMeta.habitEntryUpdatedAt[id]=now});if(!state.syncMeta.settingsUpdatedAt||(old.settings?.get('settings')&&fingerprint(old.settings.get('settings'))!==fingerprint(next.settings.get('settings'))))state.syncMeta.settingsUpdatedAt=now;return collectionsFor(state)}
export function diffCollections(before,after,now=Date.now()){
  const result=[];
  Object.keys(CLOUD_TABLES).forEach(collection=>{
    const old=before?.[collection]||new Map(),next=after?.[collection]||new Map();
    next.forEach((record,id)=>{
      if(!old.has(id)||stableStringify(old.get(id))!==stableStringify(record))result.push({type:'upsert',collection,id,record});
    });
    old.forEach((record,id)=>{
      if(!next.has(id))result.push({type:'delete',collection,id,record:{...record,deletedAt:iso(now),updatedAt:iso(now)}});
    });
  });
  return result;
}
export const queueLatest=operations=>[...operations.reduce((map,operation)=>{if(operation?.collection==='notes'&&!protectedNoteInvariant(operation.record))throw new Error('Protected note sync blocked');map.set(`${operation.collection}:${operation.id}`,operation);return map},new Map()).values()];
export const sortCloudOperations=operations=>[...operations].sort((left,right)=>CLOUD_SYNC_ORDER.indexOf(left.collection)-CLOUD_SYNC_ORDER.indexOf(right.collection));
export async function settleCloudOperations(operations,writeOperation){const succeeded=[],failed=[];for(const operation of sortCloudOperations(operations)){try{await writeOperation(operation);succeeded.push(operation)}catch(error){failed.push({operation,error})}}return{succeeded,failed}}
const newest=(left,right)=>!left?right:!right?left:time(right.deletedAt||right.updatedAt)>=time(left.deletedAt||left.updatedAt)?right:left;
function stateFromCollections(template,collections){const next=copy(template),active=key=>[...collections[key].values()].filter(record=>!record.deletedAt),asLocal=value=>localTime(value);next.tasks=active('tasks').map(row=>({id:row.id,title:row.title,date:row.date||'',duration:row.duration??null,category:row.category,priority:row.priority,challenge:row.challenge,completed:row.completed,completedAt:row.completedAt?asLocal(row.completedAt):null,createdAt:asLocal(row.createdAt),updatedAt:asLocal(row.updatedAt)}));next.habits=active('habits').map(row=>({id:row.id,title:row.title,createdAt:asLocal(row.createdAt),updatedAt:asLocal(row.updatedAt)}));next.checks={};active('habitEntries').filter(row=>row.completed).forEach(row=>(next.checks[row.habitId]||=[]).push(row.date));next.notes=active('notes').map(row=>({id:row.id,folderId:row.folderId||'',title:row.protected?'':row.title,body:row.protected?'':row.body,kind:row.kind,items:row.protected?[]:list(row.items),done:Boolean(row.done),protected:Boolean(row.protected),...(row.protected?{secure:row.secure}:{}),createdAt:asLocal(row.createdAt),updatedAt:asLocal(row.updatedAt)}));next.folders=active('folders').map(row=>({id:row.id,name:row.name,createdAt:asLocal(row.createdAt),updatedAt:asLocal(row.updatedAt)}));next.focusSessions=active('focusSessions').map(row=>({id:row.id,taskId:row.taskId,durationMinutes:row.durationMinutes,startedAt:row.startedAt,completedAt:row.completedAt,status:row.status,createdAt:asLocal(row.createdAt),updatedAt:asLocal(row.updatedAt)}));const settings=collections.settings.get('settings')?.data;if(settings)Object.assign(next,copy(settings));next.syncMeta=obj(next.syncMeta);next.syncMeta.tombstones={};Object.keys(CLOUD_TABLES).forEach(collection=>collections[collection].forEach((record,id)=>{if(record.deletedAt&&collection!=='settings')next.syncMeta.tombstones[collection+':'+id]={...record,collection}}));return next}
export function mergeStates(local,remote){const left=collectionsFor(local),right=collectionsFor(remote),merged={};Object.keys(CLOUD_TABLES).forEach(key=>{merged[key]=new Map();new Set([...left[key].keys(),...right[key].keys()]).forEach(id=>merged[key].set(id,newest(left[key].get(id),right[key].get(id))))});return stateFromCollections(local,merged)}
export function rowsToState(template,rows){const collections={tasks:new Map(),habits:new Map(),habitEntries:new Map(),notes:new Map(),folders:new Map(),focusSessions:new Map(),settings:new Map()};list(rows.tasks).forEach(row=>collections.tasks.set(row.id,{id:row.id,title:row.title,date:row.scheduled_for,duration:row.duration_minutes,category:row.category,priority:row.priority,challenge:row.challenge,completed:row.completed,completedAt:row.completed_at,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at}));list(rows.habits).forEach(row=>collections.habits.set(row.id,{id:row.id,title:row.title,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at}));list(rows.habitEntries).forEach(row=>collections.habitEntries.set(`${row.habit_id}:${row.entry_date}`,{id:`${row.habit_id}:${row.entry_date}`,habitId:row.habit_id,date:row.entry_date,completed:row.completed,updatedAt:row.updated_at,deletedAt:row.deleted_at}));list(rows.notes).forEach(row=>collections.notes.set(row.id,{id:row.id,folderId:row.folder_id,title:row.title,body:row.body,kind:row.kind,items:row.items,done:row.done,protected:row.protected,secure:row.secure,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at}));list(rows.folders).forEach(row=>collections.folders.set(row.id,{id:row.id,name:row.name,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at}));list(rows.focusSessions).forEach(row=>collections.focusSessions.set(row.id,{id:row.id,taskId:row.task_id,durationMinutes:row.duration_minutes,startedAt:row.started_at,completedAt:row.completed_at,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at}));if(list(rows.settings)[0])collections.settings.set('settings',{id:'settings',data:rows.settings[0].data||{},updatedAt:rows.settings[0].updated_at,deletedAt:rows.settings[0].deleted_at});return stateFromCollections(template,collections)}
