const { test, expect } = require('@playwright/test');
const { boot, show } = require('./theme-helpers.cjs');
test('hidden quick-capture date neither widens the dialog nor loses the chosen date', async ({ page }) => {
  await boot(page);
  await page.locator(page.viewportSize().width <= 900 ? '#mobileCreateBtn' : '#globalAddBtn').click();
  expect(await page.locator('#quickAddDialog').evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(0);
  await page.locator('#quickCaptureInput').fill('Release chosen date');
  await page.locator('#quickCaptureDate').evaluate(el => { el.value = '2026-09-20'; el.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.locator('#quickCaptureForm .primary').click();
  expect(await page.evaluate(() => SeverApp.getState().tasks.find(t => t.title === 'Release chosen date').date)).toBe('2026-09-20');
});
for (const theme of ['calm', 'cozy', 'focus']) {
  test(`${theme}: release CRUD, Undo, calendar, timer, notes, protected notes, habits, progress and settings`, async ({ page }) => {
    test.setTimeout(60000);
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await boot(page, theme);
    const mobile = page.viewportSize().width <= 900;
    await page.locator(mobile ? '#mobileCreateBtn' : '#globalAddBtn').click();
    await page.locator('#quickAddTask').click();
    await page.locator('#taskTitle').fill('Release task');
    await page.locator('#taskForm .primary').click();
    const task = page.locator('#todayTasks .task').filter({ hasText: 'Release task' });
    await expect(task).toBeVisible();
    await task.locator('.task-open').click();
    await page.locator('#taskActionEdit').click();
    await page.locator('#taskTitle').fill('Release task edited');
    await page.locator('#taskForm .primary').click();
    await expect(task).toContainText('Release task edited');
    await task.locator('.check').click();
    expect(await page.evaluate(() => SeverApp.getState().tasks.find(t => t.title === 'Release task edited').completed)).toBe(true);
    await task.locator('.task-open').click();
    await page.locator('#taskActionDelete').click();
    await expect(task).toHaveCount(0);
    await page.locator('#toast button').click();
    await expect(task).toHaveCount(1);
    expect(await page.evaluate(() => SeverApp.getState().tasks.find(t => t.title === 'Release task edited').completed)).toBe(true);

    await show(page, 'calendar');
    const before = await page.locator('#monthTitle').textContent();
    await page.locator('#prevMonth').click();
    expect(await page.locator('#monthTitle').textContent()).not.toBe(before);
    await page.locator('#nextMonth').click();
    await expect(page.locator('#monthTitle')).toHaveText(before);
    await show(page, 'timer');
    await page.locator('#timerToggle').click();
    await expect(page.locator('#timerToggle')).toHaveText('Пауза');
    await page.waitForTimeout(1100);
    await page.locator('#timerToggle').click();
    const paused = await page.locator('#timerDisplay').textContent();
    await page.waitForTimeout(1100);
    await expect(page.locator('#timerDisplay')).toHaveText(paused);
    await page.locator('#timerReset').click();
    await expect(page.locator('#timerDisplay')).toHaveText('25:00');

    await show(page, 'notes');
    if (mobile) {
      await page.locator('#mobileCreateBtn').click();
      await page.locator('#quickAddNote').click();
    } else await page.locator('#openNote').click();
    await page.locator('#noteTitle').fill('Release note');
    await page.locator('#noteBody').fill('Original body');
    await page.locator('#noteForm .primary').click();
    let note = page.locator('.note-card').filter({ hasText: 'Release note' });
    await note.locator('.note-edit').click();
    await page.locator('#noteBody').fill('Edited body');
    await page.locator('#noteForm .primary').click();
    await expect(note).toContainText('Edited body');
    await note.locator('.note-edit').click();
    await page.locator('#deleteNote').click();
    await expect(note).toHaveCount(0);
    await page.locator('#toast button').click();
    await expect(note).toContainText('Edited body');

    // Real browser WebCrypto: no crypto mocks and no real user data.
    await note.locator('.note-edit').click();
    await page.locator('#noteTitle').fill('SECRET_RELEASE_TITLE');
    await page.locator('#noteBody').fill('SECRET_RELEASE_BODY');
    await page.locator('#noteProtected').check();
    await page.locator('#notePassword').fill('Disposable-Release-Password-2026!');
    await page.locator('#noteForm .primary').click();
    await expect(page.locator('#noteDialog')).toBeHidden();
    const protectedId = await page.evaluate(() => SeverApp.getState().notes.find(n => n.protected).id);
    const secureState = await page.evaluate(() => localStorage.getItem('sever-anonymous-state-v1'));
    expect(secureState).not.toContain('SECRET_RELEASE');
    expect(secureState).not.toContain('Disposable-Release-Password');
    note = page.locator('.note-card').filter({ has: page.locator('.unlock-note') });
    await note.locator('.unlock-note').click();
    await page.locator('#unlockPassword').fill('wrong-password');
    await page.locator('#unlockForm .primary').click();
    await expect(page.locator('#unlockError')).toBeVisible();
    await page.locator('#unlockPassword').fill('Disposable-Release-Password-2026!');
    await page.locator('#unlockForm .primary').click();
    await expect(page.locator('#unlockDialog')).toBeHidden();
    note = page.locator('.note-card').filter({ hasText: 'SECRET_RELEASE_TITLE' });
    await expect(note).toContainText('SECRET_RELEASE_BODY');
    await note.locator('.note-edit').click();
    await page.locator('#noteBody').fill('SECRET_RELEASE_EDIT');
    await page.locator('#noteForm .primary').click();
    await expect(page.locator('#noteDialog')).toBeHidden();
    expect(await page.evaluate(() => localStorage.getItem('sever-anonymous-state-v1'))).not.toContain('SECRET_RELEASE');
    await page.reload();
    await page.waitForFunction(() => window.SeverNotes);
    await show(page, 'notes');
    await expect(page.locator('.unlock-note')).toBeVisible();
    await page.locator('.unlock-note').click();
    await page.locator('#unlockPassword').fill('Disposable-Release-Password-2026!');
    await page.locator('#unlockForm .primary').click();
    await expect(page.locator('.note-card').filter({ hasText: 'SECRET_RELEASE_TITLE' })).toContainText('SECRET_RELEASE_EDIT');
    expect(await page.evaluate(id => SeverApp.getState().notes.find(n => n.id === id).protected, protectedId)).toBe(true);

    await show(page, 'habits');
    await page.locator('#habitsView .habit-day:not(:disabled)').last().click();
    expect(await page.evaluate(() => Object.values(SeverApp.getState().checks).flat().length)).toBe(1);
    await show(page, 'progress');
    await expect(page.locator('#allDone')).toHaveText('1');
    await show(page, 'settings');
    await expect(page.locator(`[data-sever-theme="${theme}"]`)).toHaveAttribute('aria-checked', 'true');
    await page.locator('#lockProtectedNotesNow').click();
    await page.locator('#severAiOpen').click();
    await expect(page.locator('#severAiInput')).toBeVisible();
    await page.locator('#severAiClose').click();
    await expect(page.locator('#severAiPanel')).toBeHidden();
    expect(errors).toEqual([]);
  });
}
