const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='sever-data-v2',ANONYMOUS_KEY='sever-anonymous-state-v1',LEGACY_OWNER_KEY='sever-cloud-legacy-owner-v1',months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const dayISO=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateOf=s=>new Date(s+'T12:00:00');
const addDays=(s,n)=>{const d=dateOf(s);d.setDate(d.getDate()+n);return dayISO(d)};
const getLocalToday=()=>dayISO();
const localDayFromTimestamp=value=>{const timestamp=Number(value);return Number.isFinite(timestamp)&&timestamp>0?dayISO(new Date(timestamp)):''};
const getDaysInMonth=(year,month)=>new Date(year,month+1,0).getDate();
const monthStart=(date=new Date())=>new Date(date.getFullYear(),date.getMonth(),1);
const sameMonth=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth();
let TODAY=getLocalToday(),cursor=monthStart(),progressCursor=monthStart(),dashboardCursor=monthStart(),deferredInstall=null;
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const STORAGE_DB='sever-storage-v1',STORAGE_STORE='state';

function openStorageDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('IndexedDB недоступен'));return}const request=indexedDB.open(STORAGE_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORAGE_STORE))request.result.createObjectStore(STORAGE_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function writeStorageBackup(value){const db=await openStorageDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORAGE_STORE,'readwrite');tx.objectStore(STORAGE_STORE).put(JSON.parse(JSON.stringify(value)),storageKey);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function readStorageBackup(){const db=await openStorageDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORAGE_STORE,'readonly'),request=tx.objectStore(STORAGE_STORE).get(storageKey);request.onsuccess=()=>{db.close();resolve(request.result)};request.onerror=()=>{db.close();reject(request.error)}})}
function storageStatus(text,kind='ok'){const el=$('#storageStatus');if(!el)return;el.textContent=text;el.className=kind}

let storageKey=KEY;
function freshState(){return{version:10,onboarded:false,challengeStart:TODAY,challengeDays:0,challengeName:'',tasks:[],notes:[],habits:[],checks:{},taskMemory:[],profile:{name:''},focusSessions:[],stats:{focusMs:0,sessions:0},reminders:{enabled:false,time:'19:00',lastDate:''},security:{protectedNotesAutoLockMinutes:5,lockInBackground:true}}}
function migrate(data){if(!data?.tasks)return freshState();data.notes=Array.isArray(data.notes)?data.notes.map(note=>{if(note?.protected)return{...note,title:'',body:'',kind:'protected',items:[],done:false,protected:true};const items=Array.isArray(note.items)?note.items.map(item=>({id:item.id||uid(),text:String(item.text||''),done:Boolean(item.done)})):[];return{...note,kind:['text','checklist'].includes(note.kind)?note.kind:items.length?'checklist':'text',items,done:note.done??Number(note.progress)>=100,protected:false}}):[];data.habits=Array.isArray(data.habits)?data.habits:[];data.checks=data.checks&&typeof data.checks==='object'&&!Array.isArray(data.checks)?data.checks:{};data.taskMemory=Array.isArray(data.taskMemory)?data.taskMemory:[];data.focusSessions=Array.isArray(data.focusSessions)?data.focusSessions:[];data.profile=data.profile&&typeof data.profile==='object'?data.profile:{name:''};data.stats={focusMs:Math.max(0,Number(data.stats?.focusMs)||0),sessions:Math.max(0,Math.floor(Number(data.stats?.sessions)||0))};if(!data.focusSessions.length&&data.stats.focusMs>0)data.focusSessions=[{id:uid(),taskId:null,durationMinutes:Math.max(1,Math.round(data.stats.focusMs/60000)),startedAt:null,completedAt:data._savedAt||Date.now(),status:'completed',createdAt:data._savedAt||Date.now(),updatedAt:data._savedAt||Date.now(),legacy:true}];data.reminders=data.reminders&&typeof data.reminders==='object'?data.reminders:{enabled:false,time:'19:00',lastDate:''};data.security={protectedNotesAutoLockMinutes:[1,5,15,30].includes(Number(data.security?.protectedNotesAutoLockMinutes))?Number(data.security.protectedNotesAutoLockMinutes):5,lockInBackground:data.security?.lockInBackground!==false};data.challengeStart??=TODAY;const challenge=data.tasks.filter(t=>t.challenge);data.challengeDays??=(new Set(challenge.map(t=>t.date)).size||30);data.challengeName??=[...new Set(challenge.map(t=>t.category))].join(' + ');data.onboarded??=true;data.version=10;return data}
function readState(key=storageKey){try{const raw=localStorage.getItem(key);return raw?migrate(JSON.parse(raw)):freshState()}catch{return freshState()}}
let state=readState();
function persistLocal(){try{state._savedAt=Date.now();if(!window.SeverSecurityCore)throw new Error('Security core unavailable');const persistent=window.SeverSecurityCore.persistentState(state),serialized=JSON.stringify(persistent);let localSaved=true;try{localStorage.setItem(storageKey,serialized)}catch{localSaved=false}return writeStorageBackup(persistent).then(()=>storageStatus(localSaved?'Две копии сохранены':'Резервная копия сохранена')).catch(()=>{if(localSaved)storageStatus('Основная копия сохранена');else{storageStatus('Не удалось сохранить','error');setTimeout(()=>toast('Ошибка сохранения. Скачай резервную копию.'),0)}})}catch{storageStatus('Сохранение заблокировано проверкой безопасности','error');setTimeout(()=>toast('Не удалось безопасно сохранить данные'),0);return Promise.reject(new Error('Security invariant failed'))}}
function save(){const result=persistLocal();window.SeverApp?.onLocalSave?.();return result}
async function recoverLatestState(){try{const backup=await readStorageBackup();if(backup&&Number(backup._savedAt)>Number(state._savedAt||0)){state=migrate(backup);const persistent=window.SeverSecurityCore.persistentState(state);try{localStorage.setItem(storageKey,JSON.stringify(persistent))}catch{}toast('Данные восстановлены из резервной копии')}}catch{} }
let toastTimer=null,undoAction=null;
function toast(text,undo=null){const root=$('#toast');root.textContent='';const label=document.createElement('span');label.textContent=text;root.appendChild(label);undoAction=undo;if(undo){const button=document.createElement('button');button.type='button';button.textContent='Отменить';button.onclick=()=>{const action=undoAction;undoAction=null;clearTimeout(toastTimer);root.classList.remove('show');action?.()};root.appendChild(button)}root.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{undoAction=null;root.classList.remove('show')},undo?5000:2200)}
function saveAndRender(){save();render()}
function completeTask(task,{returnToToday=false}={}){if(!task||task.completed)return;task.completed=true;if(activeTaskId===task.id)clearActiveTask();saveAndRender();toast('Задача выполнена',()=>{task.completed=false;saveAndRender()});if(returnToToday)setTimeout(()=>switchView('today'),450)}
function deleteTask(task){if(!task)return;const index=state.tasks.findIndex(item=>item.id===task.id);if(index<0)return;state.tasks.splice(index,1);if(activeTaskId===task.id)clearActiveTask();saveAndRender();toast('Задача удалена',()=>{state.tasks.splice(Math.min(index,state.tasks.length),0,task);saveAndRender()})}
function moveTaskToTomorrow(task){if(!task)return;const previousDate=task.date;task.date=addDays(TODAY,1);saveAndRender();toast('Перенесено на завтра',()=>{task.date=previousDate;saveAndRender()})}
function pretty(s,weekday=true){return dateOf(s).toLocaleDateString('ru-RU',weekday?{weekday:'long',day:'numeric',month:'long'}:{day:'numeric',month:'long'})}
function empty(text){return `<div class="empty">${text}</div>`}
function rollover(){let moved=0;state.tasks.forEach(t=>{if(!t.challenge&&!t.completed&&t.date<TODAY){t.date=TODAY;moved++}});if(moved){save();setTimeout(()=>toast(`Перенесено на сегодня: ${moved}`),300)}}

function taskElement(t){const el=document.createElement('article'),duration=t.duration?`${t.duration} мин`:'Без времени';el.className='task '+(t.completed?'done':'');el.innerHTML=`<button class="check" aria-label="${t.completed?'Вернуть задачу':'Выполнить задачу'}">${t.completed?'✓':''}</button><button class="task-open" type="button"><span class="task-name">${t.priority?'<span class="star">★</span>':''}</span><span class="task-meta">${duration} · ${escapeText(t.category)}</span></button><button class="edit" aria-label="Действия с задачей">•••</button>`;el.querySelector('.task-name').append(document.createTextNode(t.title));el.querySelector('.check').onclick=()=>{if(t.completed){t.completed=false;saveAndRender();toast('Задача возвращена')}else completeTask(t)};el.querySelector('.task-open').onclick=()=>openTaskAction(t);el.querySelector('.edit').onclick=()=>openTaskAction(t);return el}
function fillTasks(root,list,text){const box=$(root);box.innerHTML='';if(!list.length){box.innerHTML=empty(text);return}list.sort((a,b)=>Number(b.priority)-Number(a.priority)).forEach(t=>box.appendChild(taskElement(t)))}
function challengeTasks(category){return state.tasks.filter(t=>t.challenge&&t.category===category)}
function challengeCategories(){return[...new Set(state.tasks.filter(t=>t.challenge).map(t=>t.category))]}
function renderChallenge(){const categories=challengeCategories(),block=$('#challengeBlock');block.classList.toggle('hidden',!categories.length);if(!categories.length)return;const days=state.challengeDays||30;$('#challengeTitle').textContent=state.challengeName||categories.join(' + ');const elapsed=Math.floor((dateOf(TODAY)-dateOf(state.challengeStart))/86400000)+1;$('#dayCounter').textContent=`День ${Math.min(days,Math.max(1,elapsed))}/${days}`;const root=$('#challengeProgress');root.innerHTML='';categories.forEach(category=>{const list=challengeTasks(category),done=list.filter(t=>t.completed).length,card=document.createElement('article');card.innerHTML=`<div><span></span><b>${done}/${list.length}</b></div><i><em style="width:${list.length?done/list.length*100:0}%"></em></i>`;card.querySelector('span').textContent=category;root.appendChild(card)})}

let todayFilter='all';
function focusMinutesForDate(date){return state.focusSessions.filter(session=>session.status==='completed'&&localDayFromTimestamp(session.completedAt||session.startedAt)===date).reduce((sum,session)=>sum+(Number(session.durationMinutes)||0),0)}
function renderDashboard(items,pending,next){const done=items.filter(task=>task.completed).length,percent=items.length?Math.round(done/items.length*100):0,remaining=pending.reduce((sum,task)=>sum+(Number(task.duration)||0),0),total=items.reduce((sum,task)=>sum+(Number(task.duration)||0),0),focus=focusMinutesForDate(TODAY),ring=251.33*(1-percent/100);$('#dashboardProgressValue').textContent=percent+'%';$('#dashboardProgressMeta').textContent=items.length?`${done} из ${items.length} задач выполнено`:'Пока задач нет';$('#dashboardProgressCount').textContent=items.length?`${done}/${items.length}`:'0';$('#dashboardProgressArc').style.strokeDashoffset=ring;$('#dashboardFocusValue').textContent=focus?focusTimeLabel(focus*60000):'0 мин';$('#dashboardFocusMeta').textContent=focus?`Сегодня · ${state.focusSessions.filter(session=>session.status==='completed'&&localDayFromTimestamp(session.completedAt||session.startedAt)===TODAY).length} сессии`:'Сегодня сессий ещё не было';const chart=$('#dashboardFocusChart');chart.innerHTML='';for(let offset=6;offset>=0;offset--){const value=focusMinutesForDate(addDays(TODAY,-offset)),bar=document.createElement('i');bar.style.height=`${value?Math.max(16,Math.min(100,value/2)):8}%`;bar.title=`${pretty(addDays(TODAY,-offset),false)} · ${value} мин`;chart.appendChild(bar)}$('#dashboardRemainingValue').textContent=remaining?`${remaining} мин`:'0 мин';$('#dashboardRemainingMeta').textContent=total?`Из ${total} мин запланировано`:'Нет задач с длительностью';$('#dashboardRemainingLine').style.width=total?`${Math.round(remaining/total*100)}%`:'0%';$('#dashboardNextTitle').textContent=next?.title||'Свободный день';$('#dashboardNextMeta').textContent=next?`${next.category||'Личное'} · ${next.duration?`${next.duration} мин`:'без времени'}`:'Добавьте первый шаг';const play=$('#dashboardNextStart');play.disabled=!next;play.onclick=()=>next&&startLinkedTask(next)}
function renderToday(){const items=state.tasks.filter(t=>t.date===TODAY),pending=items.filter(t=>!t.completed),plannedMinutes=pending.reduce((a,t)=>a+(Number(t.duration)||0),0),untimed=pending.filter(t=>!t.duration).length,next=pending.find(t=>t.challenge)||pending.find(t=>t.priority)||pending[0],visible=todayFilter==='pending'?pending:todayFilter==='done'?items.filter(t=>t.completed):items;fillTasks('#todayTasks',visible,todayFilter==='all'?'Сегодня всё свободно. Добавь небольшой шаг.':'В этой группе задач пока нет.');$('#todayLoad').textContent=`${plannedMinutes} мин${untimed?` · ${untimed} без времени`:''}`;$('#todayLabel').textContent=pretty(TODAY).toUpperCase();$('#todayFilterAll').textContent=items.length;$('#todayFilterPending').textContent=pending.length;$('#todayFilterDone').textContent=items.length-pending.length;$$('#todayFilters button').forEach(button=>{const active=button.dataset.filter===todayFilter;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});renderChallenge();const done=items.filter(t=>t.completed).length,percent=items.length?Math.round(done/items.length*100):0;$('#coursePercent').textContent=percent+'%';$('#courseArc').style.strokeDashoffset=264*(1-percent/100);$('#courseTitle').textContent='Прогресс на сегодня';if(next){const duration=next.duration?` — ${next.duration} минут`:'';$('#courseText').textContent=`Следующая задача: ${next.title.toLowerCase()}${duration}.`;$('#courseAction').textContent='Показать задачу';$('#courseAction').onclick=()=>$('#todayTasks').scrollIntoView({behavior:'smooth'})}else if(items.length){$('#courseText').textContent='Все задачи на сегодня выполнены. Отличный результат.';$('#courseAction').textContent='Посмотреть весь прогресс';$('#courseAction').onclick=()=>switchView('progress')}else{$('#courseText').textContent='Пока задач нет — добавь первый небольшой шаг.';$('#courseAction').textContent='Добавить задачу';$('#courseAction').onclick=()=>openTask()}renderDashboard(items,pending,next);$('#todayFocusDisplay').textContent=$('#timerDisplay').textContent;$('#todayFocusTask').textContent=next?next.title:'Выберите задачу и начните спокойную работу';const focusButton=$('#todayFocusToggle');focusButton.textContent=timerRunning?'Пауза':next?'Начать фокус':'Открыть таймер';focusButton.onclick=()=>{if(timerRunning){pauseTimer();return}if(next)startLinkedTask(next);else switchView('timer')}}

function renderCalendar(){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7;$('#monthTitle').textContent=`${months[m]} ${y}`;const root=$('#calendar');root.innerHTML='';for(let i=0;i<42;i++){const d=new Date(y,m,i-offset+1),key=dayISO(d),items=state.tasks.filter(t=>t.date===key),b=document.createElement('button');b.className='day'+(d.getMonth()!==m?' dim':'')+(key===TODAY?' today':'');b.setAttribute('aria-label',`${pretty(key,false)}, задач: ${items.length}`);b.innerHTML=`<span>${d.getDate()}</span>${items.slice(0,3).map(t=>`<u>${t.completed?'✓ ':''}${escapeText(t.title)}</u>`).join('')}`;b.onclick=()=>openDay(key);root.appendChild(b)}}
function streak(){let n=0,d=TODAY;const hasChallenge=state.tasks.some(t=>t.challenge),forDate=date=>state.tasks.filter(t=>t.date===date&&(!hasChallenge||t.challenge));const today=forDate(TODAY);if(!today.length||!today.every(t=>t.completed))d=addDays(TODAY,-1);while(true){const list=forDate(d);if(!list.length||!list.every(t=>t.completed))break;n++;d=addDays(d,-1)}return n}
function focusTimeLabel(ms){if(ms>0&&ms<60000)return'<1 мин';return Math.floor(ms/60000)+' мин'}
function renderProgress(){const completed=state.tasks.filter(t=>t.completed),planned=completed.reduce((a,t)=>a+(Number(t.duration)||0),0);$('#allDone').textContent=completed.length;$('#streak').textContent=streak()+' дней';$('#focusMinutes').textContent=focusTimeLabel(state.stats.focusMs);$('#focusSessions').textContent=state.stats.sessions+' сессий';$('#plannedMinutes').textContent=planned+' мин';const root=$('#heatmap'),hasChallenge=state.tasks.some(t=>t.challenge),span=Math.min(hasChallenge?(state.challengeDays||30):30,60),start=hasChallenge?state.challengeStart:addDays(TODAY,-29);root.innerHTML='';for(let i=0;i<span;i++){const date=addDays(start,i),list=state.tasks.filter(t=>t.date===date&&(!hasChallenge||t.challenge)),done=list.filter(t=>t.completed).length,el=document.createElement('div');el.className='heat '+(list.length&&done===list.length?'full':done?'half':'');el.title=`${pretty(date,false)}: ${done}/${list.length}`;el.textContent=i+1;root.appendChild(el)}const from=addDays(TODAY,-6),week=state.tasks.filter(t=>t.date>=from&&t.date<=TODAY),done=week.filter(t=>t.completed).length,total=week.length,p=total?Math.round(done/total*100):0;$('#reviewTitle').textContent=`${done} из ${total} задач · ${p}%`;$('#reviewText').textContent=p>=80?'Ты уверенно держишь курс. Сохраняй такой темп.':p>=50?'Хорошее движение. На следующей неделе выбери три главных шага заранее.':'Сделай план легче: оставь одну небольшую обязательную задачу на день.'}
const habitWeekLabels=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
function habitWeekStart(){return addDays(TODAY,-((dateOf(TODAY).getDay()+6)%7))}
function toggleHabitCheck(habitId,date=TODAY){const habit=state.habits.find(item=>item.id===habitId);if(!habit)return;if(date>TODAY){toast('Будущие дни можно отметить позже');return}const checks=state.checks[habitId]??[],wasCompleted=checks.includes(date);state.checks[habitId]=wasCompleted?checks.filter(item=>item!==date):[...checks,date];save();render();const dayLabel=date===TODAY?'сегодня':pretty(date,false);toast(wasCompleted?`Отметка за ${dayLabel} снята`:`Отмечено: ${dayLabel}`,()=>{state.checks[habitId]=wasCompleted?[...checks]:checks.filter(item=>item!==date);save();render()})}
function habitWeekButtons(habit){const start=habitWeekStart(),fragment=document.createDocumentFragment();habitWeekLabels.forEach((label,index)=>{const date=addDays(start,index),done=Boolean(state.checks[habit.id]?.includes(date)),future=date>TODAY,button=document.createElement('button');button.type='button';button.className=`habit-day${done?' done':''}${date===TODAY?' today':''}`;button.dataset.date=date;button.dataset.day=label;button.disabled=future;button.setAttribute('aria-pressed',String(done));button.setAttribute('aria-label',`${habit.title}: ${label}, ${pretty(date,false)} — ${future?'будущий день':done?'выполнено':'не отмечено'}`);button.title=future?`${pretty(date,false)} · будущий день`:`${pretty(date,false)} · ${done?'снять отметку':'отметить'}`;button.innerHTML=`<span>${label}</span><b>${dateOf(date).getDate()}</b><i aria-hidden="true">${done?'✓':''}</i>`;if(!future)button.onclick=()=>toggleHabitCheck(habit.id,date);fragment.appendChild(button)});return fragment}
function renderHabits(){const root=$('#habitList');root.innerHTML='';if(!state.habits.length){root.innerHTML=empty('Добавь привычку, которую хочешь повторять каждый день.');return}state.habits.forEach(habit=>{const doneToday=Boolean(state.checks[habit.id]?.includes(TODAY)),weekStart=habitWeekStart(),completedThisWeek=habitWeekLabels.reduce((total,_,index)=>total+Number(Boolean(state.checks[habit.id]?.includes(addDays(weekStart,index)))),0),el=document.createElement('article');el.className=`habit ${doneToday?'done':''}`;el.innerHTML='<div class="habit-card-head"><div><h3></h3><p class="habit-status"></p></div><span class="habit-week-total"></span></div><div class="habit-week" role="group"></div><p class="habit-help">Нажмите на день, чтобы отметить выполнение</p>';el.querySelector('h3').textContent=habit.title;el.querySelector('.habit-status').textContent=doneToday?'Сегодня выполнено':'Сегодня ещё не отмечено';el.querySelector('.habit-week-total').textContent=`${completedThisWeek}/7`;const week=el.querySelector('.habit-week');week.setAttribute('aria-label',`Неделя привычки «${habit.title}»`);week.appendChild(habitWeekButtons(habit));root.appendChild(el)})}
function noteProgress(note){const items=Array.isArray(note.items)?note.items:[];if(items.length)return Math.round(items.filter(item=>item.done).length/items.length*100);if(note.done)return 100;return Math.max(0,Math.min(100,Number(note.progress)||0))}
function setAllNoteItems(note,done){(note.items||[]).forEach(item=>item.done=done);note.done=Boolean(done&&(note.items||[]).length);note.updatedAt=Date.now()}
function renderNotes(){const root=$('#noteList');root.innerHTML='';if(!state.notes.length){root.innerHTML=empty('Заметок пока нет. Создай обычную запись или чек-лист.');return}[...state.notes].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).forEach(note=>{const items=note.items||[],isChecklist=note.kind==='checklist',progress=noteProgress(note),card=document.createElement('article');card.className=`note-card ${isChecklist?'checklist-note':'text-note'}${isChecklist&&progress===100?' complete':''}`;const progressMarkup=isChecklist?`<div class="note-ring" aria-label="Выполнено ${progress}%"><svg viewBox="0 0 80 80" aria-hidden="true"><circle class="track" cx="40" cy="40" r="34"></circle><circle class="value" cx="40" cy="40" r="34" style="stroke-dashoffset:${213.63*(1-progress/100)}"></circle></svg><b>${progress}%</b></div>`:'<span class="note-kind">ЗАМЕТКА</span>';card.innerHTML=`<div class="note-card-head"><h3></h3>${progressMarkup}</div><p class="note-body"></p><div class="note-checklist"></div><div class="note-card-footer"><time></time><div class="note-card-actions"></div></div>`;card.querySelector('h3').textContent=note.title;const body=card.querySelector('.note-body');body.textContent=note.body||(!isChecklist?'Пустая заметка':'');body.classList.toggle('hidden',!body.textContent);const checklist=card.querySelector('.note-checklist');if(isChecklist){if(items.length){items.forEach(item=>{const label=document.createElement('label');label.className='note-check'+(item.done?' done':'');label.innerHTML='<input type="checkbox"><span></span>';const checkbox=label.querySelector('input');checkbox.checked=Boolean(item.done);label.querySelector('span').textContent=item.text;checkbox.onchange=()=>{item.done=checkbox.checked;note.done=items.every(step=>step.done);note.updatedAt=Date.now();save();renderNotes()};checklist.appendChild(label)})}else checklist.innerHTML='<p class="note-empty-list">Добавь пункты через «Изменить».</p>'}const actions=card.querySelector('.note-card-actions');if(isChecklist&&items.length){const toggle=document.createElement('button');toggle.className='note-toggle-all';toggle.type='button';const allDone=items.every(item=>item.done);toggle.textContent=allDone?'Снять все':'Отметить всё';toggle.onclick=()=>{setAllNoteItems(note,!allDone);save();renderNotes();toast(allDone?'Отметки сняты':'Все пункты выполнены')};actions.appendChild(toggle)}const edit=document.createElement('button');edit.className='note-edit';edit.type='button';edit.textContent='Изменить';edit.onclick=()=>openNote(note);actions.appendChild(edit);card.querySelector('time').textContent=`Обновлено ${new Date(note.updatedAt||Date.now()).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}`;root.appendChild(card)})}
function render(){renderToday();renderCalendar();renderProgress();renderHabits();renderNotes();renderTimerTask()}
function updateNavIndicator(button=$('.bottom-nav button.active')){const indicator=$('#navIndicator');if(!indicator||!button)return;indicator.style.width=`${button.offsetWidth}px`;indicator.style.height=`${button.offsetHeight}px`;indicator.style.transform=`translate3d(${button.offsetLeft}px,${button.offsetTop}px,0)`}
function switchView(name){const buttons=$$('.bottom-nav button'),current=buttons.findIndex(button=>button.classList.contains('active')),next=buttons.findIndex(button=>button.dataset.view===name),active=buttons[next],target=$('#'+name+'View');if(!target)return;if(current===next&&active){scrollTo({top:0,behavior:'smooth'});updateNavIndicator(active);return}document.querySelector('main').dataset.direction=next<0||current<0?'forward':next>current?'forward':'back';$$('.view').forEach(view=>view.classList.toggle('active',view===target));buttons.forEach(button=>{const selected=button===active;button.classList.toggle('active',selected);if(selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});if(active)requestAnimationFrame(()=>updateNavIndicator(active));scrollTo({top:0,behavior:'smooth'});if(name==='calendar')renderCalendar();if(name==='timer')renderTimer()}
function escapeText(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function rememberTask(title){const clean=title.trim(),key=clean.toLocaleLowerCase('ru-RU');if(clean.length<2)return;const old=state.taskMemory.find(item=>item.key===key);state.taskMemory=state.taskMemory.filter(item=>item.key!==key);state.taskMemory.unshift({key,title:old?.title||clean,uses:(old?.uses||0)+1,lastUsed:Date.now()});state.taskMemory=state.taskMemory.slice(0,15);renderSuggestions()}
function renderSuggestions(){const root=$('#taskSuggestions');root.innerHTML='';state.taskMemory.slice(0,10).forEach(item=>{const option=document.createElement('option');option.value=item.title;root.appendChild(option)})}

function syncDurationOptions(){const value=Number($('#taskDuration').value)||0;$$('.duration-options button').forEach(button=>button.classList.toggle('active',Number(button.dataset.duration)===value))}
function setTaskDuration(value){$('#taskDuration').value=Number(value)>0?Number(value):'';syncDurationOptions()}
function openTask(task=null,date=TODAY){$('#taskDialogTitle').textContent=task?'Изменить задачу':'Новая задача';$('#taskId').value=task?.id||'';$('#taskTitle').value=task?.title||'';$('#taskDate').value=task?.date||date;setTaskDuration(task?.duration||0);$('#taskCategory').value=['Личное','Учёба','Работа','Другое'].includes(task?.category)?task.category:'Личное';$('#taskPriority').checked=Boolean(task?.priority);$('#deleteTask').classList.toggle('hidden',!task);$('#taskDialog').showModal()}
let taskActionId='';
function taskActionType(task){const context=`${task.category} ${task.title}`.toLocaleLowerCase('ru-RU');if(task.category==='Учёба'||/уч[её]б|python|пайтон|пдд|курс|книг|урок|экзамен/.test(context))return{button:'Начать обучение',hint:'Откроется таймер для спокойной учебной сессии.'};if(task.category==='Работа'||/работ|отч[её]т|клиент|созвон|смена/.test(context))return{button:'Начать работу',hint:'Откроется таймер, чтобы сосредоточиться на этой работе.'};return{button:'Начать выполнение',hint:'Откроется таймер для выполнения этой задачи.'}}
function openTaskAction(task){taskActionId=task.id;const action=taskActionType(task),duration=task.duration?`${task.duration} мин`:'без времени',timerHint=task.duration?` Таймер установится на ${task.duration} мин.`:` Время не указано — используем выбранные в таймере ${timerMinutes} мин.`;$('#taskActionCategory').textContent=(task.category||'Задача').toLocaleUpperCase('ru-RU');$('#taskActionTitle').textContent=task.title;$('#taskActionMeta').textContent=`${pretty(task.date,false)} · ${duration}`;$('#taskActionHint').textContent=task.completed?'Эта задача уже выполнена. При необходимости её можно вернуть в список.':action.hint+timerHint;$('#taskActionStart').textContent=task.completed?'Вернуть в план':action.button;$('#taskActionComplete').classList.toggle('hidden',task.completed);$('#taskActionMove').classList.toggle('hidden',task.completed);$('#taskActionStart').classList.toggle('secondary',task.completed);$('#taskActionDialog').showModal()}
function parseQuick(text){let date=TODAY;if(/(^|\s)завтра(?=\s|$|[.,!?])/i.test(text))date=addDays(TODAY,1);const durationMatch=text.match(/(\d{1,3})\s*(?:минут(?:а|ы|у)?|мин)(?=\s|$|[.,!?])/i),duration=durationMatch?Number(durationMatch[1]):null;let title=text.replace(/^(добавь|запиши|создай)\s*/i,'').replace(/(^|\s)(сегодня|завтра)(?=\s|$|[.,!?])/ig,'$1').replace(/\d{1,3}\s*(?:минут(?:а|ы|у)?|мин)(?=\s|$|[.,!?])/ig,'').replace(/\s+/g,' ').trim();const category=/python|пайтон/i.test(title)?'Учёба':/пдд/i.test(title)?'Учёба':'Личное';return{title:title||text,date,duration,category,challenge:false,completed:false,priority:false,id:uid()}}
let selectedDay=TODAY;
function openDay(date){selectedDay=date;const items=state.tasks.filter(task=>task.date===date);$('#dayDialogTitle').textContent=pretty(date);$('#dayDialogMeta').textContent=items.length?`${items.filter(task=>!task.completed).length} осталось · ${items.filter(task=>task.completed).length} выполнено`:'Пока здесь ничего нет.';fillTasks('#dayTaskList',items,'Добавь первую задачу на этот день.');$('#dayDialog').showModal()}


$('#quickForm').onsubmit=e=>{e.preventDefault();const text=$('#quickInput').value.trim();if(!text)return;const task=parseQuick(text);state.tasks.push(task);rememberTask(task.title);save();$('#quickInput').value='';render();toast('Добавлено')};
$('#openAdd').onclick=()=>openTask();
$('#todayAddTask').onclick=()=>openTask();
$$('#todayFilters button').forEach(button=>button.onclick=()=>{todayFilter=button.dataset.filter;renderToday()});
$$('[data-close]').forEach(b=>{b.setAttribute('aria-label','Закрыть');b.onclick=()=>$('#'+b.dataset.close).close()});
$('#taskForm').onsubmit=e=>{e.preventDefault();const id=$('#taskId').value,existing=state.tasks.find(t=>t.id===id),rawDuration=$('#taskDuration').value.trim(),data={title:$('#taskTitle').value.trim(),date:$('#taskDate').value,duration:rawDuration?Math.max(1,Math.min(600,Number(rawDuration))):null,category:$('#taskCategory').value,priority:$('#taskPriority').checked};if(existing)Object.assign(existing,data);else state.tasks.push({id:uid(),...data,challenge:false,completed:false});rememberTask(data.title);save();$('#taskDialog').close();render();toast('Сохранено')};
$('#deleteTask').onclick=()=>{const task=state.tasks.find(item=>item.id===$('#taskId').value);$('#taskDialog').close();deleteTask(task)};
$('#taskActionComplete').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();completeTask(task)};
$('#taskActionMove').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();moveTaskToTomorrow(task)};
$('#taskActionDelete').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();deleteTask(task)};
$('#dayAddTask').onclick=()=>{const date=selectedDay;$('#dayDialog').close();openTask(null,date)};
let quickCaptureOffset=0;
function syncQuickCaptureDate(){const date=addDays(TODAY,quickCaptureOffset);$('#quickCaptureDate').value=date;$$('[data-quick-date]').forEach(button=>{const active=Number(button.dataset.quickDate)===quickCaptureOffset;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
$('#globalAddBtn').onclick=()=>{quickCaptureOffset=0;$('#quickCaptureForm').reset();syncQuickCaptureDate();$('#quickAddDialog').showModal();requestAnimationFrame(()=>$('#quickCaptureInput').focus())};$('#quickAddTask').onclick=()=>{$('#quickAddDialog').close();openTask()};$('#quickAddNote').onclick=()=>{$('#quickAddDialog').close();switchView('notes');openNote()};$$('[data-open-view]').forEach(button=>button.onclick=()=>{$('#moreDialog').close();switchView(button.dataset.openView)});$$('[data-quick-date]').forEach(button=>button.onclick=()=>{quickCaptureOffset=Number(button.dataset.quickDate);syncQuickCaptureDate()});$('#quickCaptureChooseDate').onclick=()=>$('#quickCaptureDate').showPicker?.();$('#quickCaptureDate').onchange=()=>{const chosen=$('#quickCaptureDate').value;if(chosen){quickCaptureOffset=Math.round((dateOf(chosen)-dateOf(TODAY))/86400000);$$('[data-quick-date]').forEach(button=>button.classList.remove('active'))}};$('#quickCaptureForm').onsubmit=event=>{event.preventDefault();const text=$('#quickCaptureInput').value.trim();if(!text)return;const task=parseQuick(text),parsedTomorrow=/(^|\s)завтра(?=\s|$|[.,!?])/i.test(text);task.date=quickCaptureOffset===0&&parsedTomorrow?task.date:$('#quickCaptureDate').value||task.date;state.tasks.push(task);rememberTask(task.title);save();render();$('#quickAddDialog').close();toast('Задача добавлена')};
$$('.duration-options button').forEach(button=>button.onclick=()=>setTaskDuration(Number(button.dataset.duration)));$('#taskDuration').oninput=syncDurationOptions;
$('#taskActionEdit').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();if(task)openTask(task)};
$('#taskActionStart').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();if(!task)return;if(task.completed){task.completed=false;saveAndRender();toast('Задача возвращена')}else startLinkedTask(task)};
let editingNoteItems=[];
let editingNoteType='text';
function setNoteType(type){editingNoteType=type==='checklist'?'checklist':'text';$$('[data-note-type]').forEach(button=>button.classList.toggle('active',button.dataset.noteType===editingNoteType));$('#checklistEditor').classList.toggle('hidden',editingNoteType!=='checklist');$('#noteBodyLabel').textContent=editingNoteType==='checklist'?'Описание — необязательно':'Текст заметки';$('#noteBody').placeholder=editingNoteType==='checklist'?'Например: дела на сегодня':'Запиши мысли или важную информацию';if(editingNoteType==='checklist'&&!editingNoteItems.length){editingNoteItems.push({id:uid(),text:'',done:false});renderNoteItemsEditor()}}
function renderNoteItemsEditor(){const root=$('#noteItemsEditor');root.innerHTML='';editingNoteItems.forEach((item,index)=>{const row=document.createElement('div');row.className='note-item-editor';row.innerHTML='<input type="checkbox" aria-label="Пункт выполнен"><input type="text" maxlength="160" placeholder="Например: уборка"><button type="button" aria-label="Удалить пункт">×</button>';const checkbox=row.children[0],input=row.children[1],remove=row.children[2];checkbox.checked=Boolean(item.done);checkbox.onchange=()=>item.done=checkbox.checked;input.value=item.text;input.oninput=()=>item.text=input.value;input.onkeydown=event=>{if(event.key!=='Enter')return;event.preventDefault();item.text=input.value;editingNoteItems.splice(index+1,0,{id:uid(),text:'',done:false});renderNoteItemsEditor();$$('#noteItemsEditor input[type="text"]')[index+1]?.focus()};remove.onclick=()=>{editingNoteItems.splice(index,1);renderNoteItemsEditor()};root.appendChild(row)})}
function openNote(note=null){$('#noteDialogTitle').textContent=note?'Изменить заметку':'Новая заметка';$('#noteId').value=note?.id||'';$('#noteTitle').value=note?.title||'';$('#noteBody').value=note?.body||'';editingNoteItems=(note?.items||[]).map(item=>({...item}));$('#deleteNote').classList.toggle('hidden',!note);setNoteType(note?.kind||((note?.items||[]).length?'checklist':'text'));renderNoteItemsEditor();$('#noteDialog').showModal()}
$$('[data-note-type]').forEach(button=>button.onclick=()=>setNoteType(button.dataset.noteType));$('#openNote').onclick=()=>openNote();$('#addNoteItem').onclick=()=>{editingNoteItems.push({id:uid(),text:'',done:false});renderNoteItemsEditor();const inputs=$$('#noteItemsEditor input[type="text"]');inputs.at(-1)?.focus()};$('#noteForm').onsubmit=e=>{e.preventDefault();const id=$('#noteId').value,existing=state.notes.find(note=>note.id===id),items=editingNoteItems.map(item=>({id:item.id||uid(),text:item.text.trim(),done:Boolean(item.done)})).filter(item=>item.text),data={title:$('#noteTitle').value.trim(),body:$('#noteBody').value.trim(),kind:editingNoteType,items,done:editingNoteType==='checklist'&&items.length?items.every(item=>item.done):false,updatedAt:Date.now()};if(existing){Object.assign(existing,data);delete existing.progress}else state.notes.push({id:uid(),...data,createdAt:Date.now()});save();renderNotes();$('#noteDialog').close();toast(editingNoteType==='checklist'?'Чек-лист сохранён':'Заметка сохранена')};$('#deleteNote').onclick=()=>{const id=$('#noteId').value;state.notes=state.notes.filter(note=>note.id!==id);save();renderNotes();$('#noteDialog').close();toast('Заметка удалена')};
$('#openHabit').onclick=()=>$('#habitDialog').showModal();$('#habitForm').onsubmit=e=>{e.preventDefault();const id=uid();state.habits.push({id,title:$('#habitTitle').value.trim()});state.checks[id]=[];save();$('#habitTitle').value='';$('#habitDialog').close();renderHabits();toast('Привычка добавлена')};$$('.bottom-nav button').forEach(button=>button.onclick=()=>switchView(button.dataset.view));window.addEventListener('resize',()=>requestAnimationFrame(()=>updateNavIndicator()),{passive:true});$('#prevMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('sever-theme',theme);$('#themeBtn').dataset.theme=theme;$('#themeBtn').setAttribute('aria-label',theme==='dark'?'Включить светлую тему':'Включить тёмную тему');document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#050505':'#f5f5f5'}$('#themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');applyTheme(document.documentElement.dataset.theme);
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function exportBackup(){try{downloadJson(window.SeverSecurityCore.createBackup(state),`sever-backup-${TODAY}.json`);toast('Резервная копия создана')}catch{toast('Экспорт заблокирован проверкой безопасности')}}
function exportProtectedVault(){try{downloadJson(window.SeverSecurityCore.createVaultExport(state),`sever-vault-${TODAY}.json`);toast('Зашифрованные данные экспортированы')}catch{toast('Экспорт защищённых данных не выполнен')}}
async function importBackup(event){try{const file=event.target.files?.[0];if(!file)return;if(file.size>window.SeverSecurityCore.MAX_BACKUP_BYTES)throw 0;const data=window.SeverSecurityCore.parseBackupText(await file.text());window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason:'restore'}}));state=migrate(data);await save();render();$('#moreDialog').close();toast('Данные восстановлены')}catch{toast('Неверный или повреждённый файл копии')}finally{event.target.value=''}}
async function resetPlanner(){window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason:'reset'}}));state=migrate(freshState());await save();render();$('#moreDialog').close();$('#welcomeDialog').showModal();toast('Данные планера удалены')}
$('#moreBtn').onclick=()=>{syncReminderUI();$('#moreDialog').showModal()};$('#exportBtn').onclick=exportBackup;$('#importInput').onchange=importBackup;$('#resetBtn').onclick=()=>{if(confirm('Удалить все данные и настроить SEVER заново?'))resetPlanner()};
const reminderMessages=[['Твой курс ждёт','Начни с одного маленького шага — дальше будет легче.'],['Не забудь про план','Даже 10 минут сегодня сохраняют движение вперёд.'],['Время держать курс','Открой SEVER и выполни ближайшую задачу.'],['Небольшой шаг важен','Не нужен идеальный день — достаточно начать.'],['Продолжим серию?','Отметь выполненное и сохрани свой темп.'],['SEVER напоминает','Твоя цель становится ближе после каждого занятия.']];
function notificationSupport(){return'Notification'in window&&'serviceWorker'in navigator}
async function showReminder(force=false){if(!notificationSupport()||Notification.permission!=='granted')return false;const pending=state.tasks.filter(t=>t.date===TODAY&&!t.completed),index=(new Date().getDate()+pending.length)%reminderMessages.length,[title,base]=reminderMessages[index],body=pending.length?`${base} Осталось задач: ${pending.length}.`:'Все задачи выполнены — отличный курс на сегодня.';const registration=await navigator.serviceWorker.ready;await registration.showNotification(title,{body,icon:'./icon-192.png',badge:'./icon-192.png',tag:force?'sever-test':'sever-daily',renotify:true,data:{url:'./'}});return true}
function syncReminderUI(){const r=state.reminders;$('#notificationToggle').checked=Boolean(r.enabled);$('#notificationTime').value=r.time||'19:00';$('#notificationHint').textContent=!notificationSupport()?'Этот браузер не поддерживает уведомления.':r.enabled?'Напоминание сработает, пока SEVER открыт. Для закрытого приложения нужны серверные push-уведомления.':'Включи напоминания и разреши их в браузере.'}
async function enableNotifications(){if(!notificationSupport()){toast('Уведомления не поддерживаются');return false}const permission=await Notification.requestPermission();if(permission!=='granted'){toast('Разрешение не выдано');return false}return true}
function checkReminder(){if(!state.reminders.enabled||state.reminders.lastDate===TODAY)return;const now=new Date(),current=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;if(current>=state.reminders.time)showReminder().then(shown=>{if(shown){state.reminders.lastDate=TODAY;save()}})}
$('#moreBtn').onclick=()=>{syncReminderUI();$('#moreDialog').showModal()};$('#notificationToggle').onchange=async e=>{if(e.target.checked&&!await enableNotifications())e.target.checked=false;state.reminders.enabled=e.target.checked;save();syncReminderUI();if(e.target.checked)toast('Напоминания включены')};$('#notificationTime').onchange=e=>{state.reminders.time=e.target.value||'19:00';state.reminders.lastDate='';save();toast('Время сохранено')};$('#testNotification').onclick=async()=>{if(await enableNotifications()){await showReminder(true);toast('Проверочное уведомление отправлено')}};
function beginCourse(goals,days,minutes){const tasks=[];for(let i=0;i<days;i++)goals.forEach(goal=>tasks.push({id:uid(),title:goal,date:addDays(TODAY,i),duration:minutes,category:goal,challenge:true,completed:false,priority:true}));state={version:8,onboarded:true,challengeStart:TODAY,challengeDays:days,challengeName:goals.join(' + '),tasks,notes:[],habits:[],checks:{},taskMemory:goals.map(title=>({key:title.toLocaleLowerCase('ru-RU'),title,uses:1,lastUsed:Date.now()})),stats:{focusMs:0,sessions:0},reminders:{enabled:false,time:'19:00',lastDate:''}};save();renderSuggestions();render();$('#welcomeDialog').close();toast('Цель создана')}
$('#welcomeForm').onsubmit=e=>{e.preventDefault();const goals=[$('#goalOne').value.trim(),$('#goalTwo').value.trim()].filter(Boolean),days=Math.max(1,Math.min(365,+$('#challengeDays').value)),minutes=Math.max(5,Math.min(600,+$('#challengeMinutes').value));beginCourse(goals,days,minutes)};$('#startEmpty').onclick=()=>{state.onboarded=true;save();render();$('#welcomeDialog').close();toast('Планер готов')};
const tourSlides=[
  { title: 'Добро пожаловать в Север', text: 'Планируй день, следи за задачами и сохраняй всё важное в одном месте.', view: 'today', target: null },
  { title: 'Сегодня', text: 'Здесь находятся задачи на текущий день. Отмечай выполненные дела — прогресс обновится автоматически.', view: 'today', target: 'today' },
  { title: 'Создавай быстро', text: 'На экране «Сегодня» нажатие + открывает создание новой задачи. Остальные действия доступны там, где они нужны.', view: 'today', target: 'create' },
  { title: 'Сфокусируйся', text: 'Запусти таймер прямо из задачи. Когда связанная сессия закончится, Север отметит задачу выполненной.', view: 'timer', target: 'timer' },
  { title: 'Всё готово', text: 'Добавь первое дело — дальше Север поможет держать спокойный и понятный темп.', view: 'today', target: null }
];
let tourIndex=0,guideManual=false,guideReturnFocus=null,guideAutomaticPending=false,guideCloudReady=false,guideShown=false;
const guideReducedMotion=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const guideIsPhone=()=>window.matchMedia?.('(max-width: 900px)').matches;
function guideTargetFor(slide){
  if(!slide.target)return null;
  if(slide.target==='today')return document.querySelector(guideIsPhone()?'.bottom-nav button[data-view="today"]':'.side-nav button[data-view="today"]');
  if(slide.target==='create')return document.querySelector(guideIsPhone()?'#mobileHeaderAction':'#globalAddBtn');
  if(slide.target==='timer')return document.querySelector(guideIsPhone()?'.bottom-nav button[data-view="timer"]':'.side-nav button[data-view="timer"]');
  return null;
}
function positionGuideTarget(){
  const dialog=$('#tourDialog'),spot=$('#guideSpotlight'),target=guideTargetFor(tourSlides[tourIndex]);
  if(!dialog?.open||!spot)return;
  if(!target||target.classList.contains('hidden')){dialog.dataset.hasTarget='false';return}
  target.scrollIntoView({block:'nearest',inline:'nearest',behavior:guideReducedMotion()?'auto':'smooth'});
  requestAnimationFrame(()=>requestAnimationFrame(()=>{
    const rect=target.getBoundingClientRect(),gap=6;
    spot.style.left=`${Math.max(0,rect.left-gap)}px`;
    spot.style.top=`${Math.max(0,rect.top-gap)}px`;
    spot.style.width=`${Math.min(window.innerWidth,rect.width+gap*2)}px`;
    spot.style.height=`${Math.min(window.innerHeight,rect.height+gap*2)}px`;
    spot.style.borderRadius=getComputedStyle(target).borderRadius||'15px';
    dialog.dataset.hasTarget='true';
  }));
}
function renderTour(){
  const slide=tourSlides[tourIndex],dialog=$('#tourDialog'),copy=$('#guideCopy');
  if(slide.view)switchView(slide.view);
  $('#tourTitle').textContent=slide.title;
  $('#tourText').textContent=slide.text;
  $('#tourBack').disabled=tourIndex===0;
  $('#tourNext').textContent=tourIndex===tourSlides.length-1?'Начать':'Далее';
  $('#tourSkip').textContent=guideManual?'Закрыть':'Пропустить';
  $('#tourDots').innerHTML=tourSlides.map((_,index)=>`<i class="${index===tourIndex?'active':''}" aria-hidden="true"></i>`).join('');
  dialog.dataset.step=String(tourIndex+1);
  copy?.classList.add('is-changing');
  requestAnimationFrame(()=>copy?.classList.remove('is-changing'));
  positionGuideTarget();
}
function closeGuide({complete=false}={}){
  const dialog=$('#tourDialog');
  if(!dialog?.open)return;
  const shouldPersist=complete&&!guideManual;
  if(shouldPersist){state.onboarded=true;state.tourSeen=true;save()}
  dialog.close();
  dialog.dataset.hasTarget='false';
  if(complete)switchView('today');
  const returnFocus=guideReturnFocus;
  guideReturnFocus=null;
  if(returnFocus?.isConnected)setTimeout(()=>returnFocus.focus({preventScroll:true}),0);
}
function startGuide({manual=false}={}){
  const dialog=$('#tourDialog');
  if(!dialog||dialog.open)return;
  guideManual=Boolean(manual);
  guideReturnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;
  $('#moreDialog')?.close();
  $('#mobileMenuSheet')?.close();
  tourIndex=0;
  dialog.showModal();
  renderTour();
  requestAnimationFrame(()=>$('#tourNext')?.focus({preventScroll:true}));
}
function maybeStartAutomaticGuide(){
  if(!guideCloudReady||!guideAutomaticPending||guideShown||state.onboarded)return;
  guideShown=true;
  requestAnimationFrame(()=>startGuide());
}
$('#tourNext').onclick=()=>{if(tourIndex<tourSlides.length-1){tourIndex+=1;renderTour()}else closeGuide({complete:true})};
$('#tourBack').onclick=()=>{if(tourIndex>0){tourIndex-=1;renderTour()}};
$('#tourSkip').onclick=()=>closeGuide({complete:!guideManual});
$('#tourDialog').addEventListener('cancel',event=>{event.preventDefault();closeGuide({complete:!guideManual})});
window.addEventListener('resize',()=>{if($('#tourDialog')?.open)positionGuideTarget()},{passive:true});
window.addEventListener('scroll',()=>{if($('#tourDialog')?.open)positionGuideTarget()},{passive:true});
window.addEventListener('sever:cloud-ready',()=>{guideCloudReady=true;maybeStartAutomaticGuide()});
$('#openGuideFromMore')?.addEventListener('click',()=>startGuide({manual:true}));
function readTimerState(){try{return JSON.parse(localStorage.getItem('sever-timer-state'))||{}}catch{return{}}}
const savedTimer=readTimerState();
let activeTaskId=localStorage.getItem('sever-active-task')||'';
let timerMinutes=Math.max(1,Math.min(600,Number(savedTimer.minutes)||25)),timerEnd=Number(savedTimer.end)||0,timerRunning=Boolean(savedTimer.running&&timerEnd>Date.now()),timerLeft=timerRunning?Math.max(0,Math.ceil((timerEnd-Date.now())/1000)):Number.isFinite(Number(savedTimer.left))?Math.max(0,Number(savedTimer.left)):timerMinutes*60,timerInterval=null,timerTrackedAt=timerRunning?Date.now():0,lastFocusPersistAt=Date.now();
function saveTimerState(){localStorage.setItem('sever-timer-state',JSON.stringify({minutes:timerMinutes,left:timerLeft,end:timerEnd,running:timerRunning}))}
function renderTimerTask(){const task=state.tasks.find(item=>item.id===activeTaskId&&!item.completed),block=$('#activeTimerTask');if(!task){activeTaskId='';localStorage.removeItem('sever-active-task');block.classList.add('hidden');return}block.classList.remove('hidden');$('#timerTaskTitle').textContent=task.title}
function clearActiveTask(){activeTaskId='';localStorage.removeItem('sever-active-task');renderTimerTask()}
function renderTimer(){const minutes=Math.floor(timerLeft/60),seconds=timerLeft%60,total=timerMinutes*60,progress=total?timerLeft/total:0,display=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;$('#timerDisplay').textContent=display;$('#timerProgress').style.strokeDashoffset=490.09*(1-progress);$('#timerToggle').textContent=timerRunning?'Пауза':timerLeft===0?'Заново':'Начать';$('.focus-card').classList.toggle('running',timerRunning);$('#timerStatus').textContent=timerRunning?'Фокус включён. Держи внимание на одной задаче.':timerLeft===0?'Сессия завершена — можно немного отдохнуть.':'Выбери время и начни спокойную работу';const mini=$('#todayFocusDisplay'),miniButton=$('#todayFocusToggle');if(mini)mini.textContent=display;if(miniButton)miniButton.textContent=timerRunning?'Пауза':'Начать';renderTimerTask()}
function trackFocusElapsed(){if(!timerRunning||!timerTrackedAt)return;const now=Date.now(),elapsed=Math.max(0,Math.min(now-timerTrackedAt,timerLeft*1000));state.stats.focusMs+=elapsed;timerTrackedAt=now;if(now-lastFocusPersistAt>=15000){lastFocusPersistAt=now;save()}}
function timerTick(){trackFocusElapsed();timerLeft=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));renderTimer();if(timerLeft===0){timerRunning=false;timerTrackedAt=0;state.stats.sessions++;clearInterval(timerInterval);timerInterval=null;saveTimerState();const task=state.tasks.find(item=>item.id===activeTaskId&&!item.completed);if(task){completeTask(task,{returnToToday:true});clearActiveTask()}else{save();renderTimer();renderProgress();toast('Фокус-сессия завершена')}if(notificationSupport()&&Notification.permission==='granted')showReminder(true)}}
function startTimer(){if(timerLeft===0)timerLeft=timerMinutes*60;timerRunning=true;timerEnd=Date.now()+timerLeft*1000;timerTrackedAt=Date.now();clearInterval(timerInterval);timerInterval=setInterval(timerTick,250);saveTimerState();renderTimer()}
function pauseTimer(){timerTick();timerRunning=false;timerTrackedAt=0;clearInterval(timerInterval);timerInterval=null;saveTimerState();save();renderTimer();renderProgress()}
function setTimerMinutes(minutes){if(timerRunning)pauseTimer();timerMinutes=Math.max(1,Math.min(600,minutes));timerLeft=timerMinutes*60;timerEnd=0;saveTimerState();$$('.timer-presets button').forEach(item=>item.classList.toggle('active',+item.dataset.minutes===timerMinutes));renderTimer()}
function startLinkedTask(task){if(timerRunning)pauseTimer();activeTaskId=task.id;localStorage.setItem('sever-active-task',activeTaskId);if(task.duration)setTimerMinutes(task.duration);else{timerLeft=timerMinutes*60;timerEnd=0;saveTimerState();renderTimer()}switchView('timer');startTimer();toast(`${taskActionType(task).button}: ${task.title}`)}
$('#timerToggle').onclick=()=>timerRunning?pauseTimer():startTimer();$('#timerReset').onclick=()=>{if(timerRunning)pauseTimer();timerLeft=timerMinutes*60;timerEnd=0;saveTimerState();renderTimer()};$$('.timer-presets button').forEach(button=>button.onclick=()=>setTimerMinutes(+button.dataset.minutes));$('#customTimerForm').onsubmit=e=>{e.preventDefault();const minutes=+$('#customMinutes').value;if(!Number.isFinite(minutes)||minutes<1)return;setTimerMinutes(minutes);$('#customMinutes').value='';toast(`Таймер установлен: ${timerMinutes} мин`)};
$('#completeTimerTask').onclick=()=>{const task=state.tasks.find(item=>item.id===activeTaskId);if(!task){clearActiveTask();return}if(timerRunning)pauseTimer();clearActiveTask();completeTask(task,{returnToToday:true})};
$('#cancelTimerTask').onclick=()=>{if(timerRunning)pauseTimer();clearActiveTask();timerLeft=timerMinutes*60;timerEnd=0;saveTimerState();renderTimer();toast('Фокус отменён — задача осталась в плане')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const registration=await navigator.serviceWorker.register('./sw.js');const showUpdate=worker=>{const root=$('#pwaSecurityUpdate');if(!root||!worker)return;root.classList.remove('hidden');$('#applyPwaUpdate').onclick=()=>worker.postMessage({type:'SKIP_WAITING'})};if(registration.waiting)showUpdate(registration.waiting);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate(worker)})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())});
window.addEventListener('pagehide',()=>{trackFocusElapsed();window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason:'pagehide'}}));try{state._savedAt=Date.now();localStorage.setItem(storageKey,JSON.stringify(window.SeverSecurityCore.persistentState(state)))}catch{}});
async function initializeApp(){await recoverLatestState();rollover();render();renderSuggestions();$$('.timer-presets button').forEach(item=>item.classList.toggle('active',+item.dataset.minutes===timerMinutes));renderTimer();requestAnimationFrame(()=>updateNavIndicator());if(timerRunning)timerInterval=setInterval(timerTick,250);syncReminderUI();checkReminder();setInterval(checkReminder,30000);guideAutomaticPending=!state.onboarded;await save();guideCloudReady=Boolean(window.SeverCloudReady);maybeStartAutomaticGuide()}
initializeApp();
window.dispatchEvent(new Event('sever:ready'));
function refreshToday(){const next=getLocalToday();if(next===TODAY)return TODAY;const previousMonth=monthStart(dateOf(TODAY));TODAY=next;const currentMonth=monthStart();if(sameMonth(cursor,previousMonth))cursor=currentMonth;if(sameMonth(progressCursor,previousMonth))progressCursor=currentMonth;return TODAY}
function taskCompletionDay(task){return task.date}
function progressForDate(date){const tasks=state.tasks.filter(task=>task.date===date),completed=tasks.filter(task=>task.completed&&taskCompletionDay(task)===date).length;return{total:tasks.length,completed,rate:tasks.length?Math.round(completed/tasks.length*100):0}}
function progressTooltip(date,summary){if(date>getLocalToday())return`${pretty(date,false)}\nБудущий день`;if(!summary.total)return`${pretty(date,false)}\nЗадач не было`;return`${pretty(date,false)}\nВыполнено: ${summary.completed} из ${summary.total} задач\n${summary.rate}%`}
function renderProgress(){refreshToday();const completed=state.tasks.filter(task=>task.completed),planned=completed.reduce((sum,task)=>sum+(Number(task.duration)||0),0),year=progressCursor.getFullYear(),month=progressCursor.getMonth(),today=getLocalToday(),todayMonth=monthStart(),root=$('#heatmap');$('#allDone').textContent=completed.length;$('#streak').textContent=streak()+' дней';$('#focusMinutes').textContent=focusTimeLabel(state.stats.focusMs);$('#focusSessions').textContent=state.stats.sessions+' сессий';$('#plannedMinutes').textContent=planned+' мин';$('#progressMonthTitle').textContent=`${months[month]} ${year}`;$('#nextProgressMonth').disabled=sameMonth(progressCursor,todayMonth);root.innerHTML='';for(let day=1;day<=getDaysInMonth(year,month);day++){const date=dayISO(new Date(year,month,day)),summary=progressForDate(date),future=date>today,level=summary.total?`rate-${summary.rate?Math.ceil(summary.rate/25):0}`:'empty-day',cell=document.createElement('button'),tooltip=progressTooltip(date,summary);cell.type='button';cell.className=`heat ${future?'future':level}`;cell.textContent=day;cell.title=tooltip;cell.dataset.tooltip=tooltip;cell.setAttribute('aria-label',tooltip.replaceAll('\n',' '));cell.onclick=()=>openDay(date);root.appendChild(cell)}const from=addDays(today,-6),week=state.tasks.filter(task=>task.date>=from&&task.date<=today),done=week.filter(task=>task.completed&&taskCompletionDay(task)===task.date).length,total=week.length,rate=total?Math.round(done/total*100):0;$('#reviewTitle').textContent=`${done} из ${total} задач · ${rate}%`;$('#reviewText').textContent=rate>=80?'Ты уверенно держишь курс. Сохраняй такой темп.':rate>=50?'Хорошее движение. На следующей неделе выбери три главных шага заранее.':'Сделай план легче: оставь одну небольшую обязательную задачу на день.'}
function completeTask(task,{returnToToday=false,timerCompleted=false}={}){if(!task||task.completed)return;task.completed=true;task.completedAt=Date.now();if(activeTaskId===task.id)clearActiveTask();saveAndRender();toast(timerCompleted?`${timerMinutes} минут завершено · задача выполнена`:'Задача выполнена',()=>{task.completed=false;task.completedAt=null;saveAndRender()});if(returnToToday)setTimeout(()=>switchView('today'),450)}
function timerTick(){trackFocusElapsed();timerLeft=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));renderTimer();if(timerLeft!==0)return;timerRunning=false;timerTrackedAt=0;state.stats.sessions++;clearInterval(timerInterval);timerInterval=null;saveTimerState();const task=state.tasks.find(item=>item.id===activeTaskId&&!item.completed);if(task){completeTask(task,{returnToToday:true,timerCompleted:true});clearActiveTask()}else{save();renderTimer();renderProgress();toast('Фокус-сессия завершена')}if(notificationSupport()&&Notification.permission==='granted')showReminder(true)}
function render(){refreshToday();renderToday();renderCalendar();renderProgress();renderHabits();renderNotes();renderTimerTask()}
$('#prevProgressMonth').onclick=()=>{progressCursor=new Date(progressCursor.getFullYear(),progressCursor.getMonth()-1,1);renderProgress()};
$('#nextProgressMonth').onclick=()=>{const next=new Date(progressCursor.getFullYear(),progressCursor.getMonth()+1,1);if(next<=monthStart()){progressCursor=next;renderProgress()}};
document.addEventListener('pointerup',event=>{if(event.target.closest('input,textarea,[contenteditable="true"]'))return;const selection=window.getSelection();if(selection?.type==='Caret')selection.removeAllRanges()});
function normalizeTaskHistory(task){const date=typeof task.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(task.date)?task.date:getLocalToday(),completed=Boolean(task.completed),completedAt=completed?(Number(task.completedAt)||dateOf(date).getTime()):null;return{...task,date,completed,completedAt}}
state.tasks=state.tasks.map(normalizeTaskHistory);
let observedDay=TODAY;setInterval(()=>{const next=getLocalToday();if(next===observedDay)return;const previousMonth=monthStart(dateOf(observedDay));observedDay=TODAY=next;if(sameMonth(cursor,previousMonth))cursor=monthStart();if(sameMonth(progressCursor,previousMonth))progressCursor=monthStart();rollover();render();checkReminder()},60000);
const migrateLegacyState=migrate;
migrate=data=>{const migrated=migrateLegacyState(data);migrated.tasks=migrated.tasks.map(normalizeTaskHistory);migrated.version=10;return migrated};
function taskElement(t){const el=document.createElement('article'),duration=t.duration?`${t.duration} мин`:'Без времени';el.className='task '+(t.completed?'done':'');el.innerHTML=`<button class="check" aria-label="${t.completed?'Вернуть задачу':'Выполнить задачу'}">${t.completed?'✓':''}</button><button class="task-open" type="button"><span class="task-name">${t.priority?'<span class="star">★</span>':''}</span><span class="task-meta">${duration} · ${escapeText(t.category)}</span></button><button class="edit" aria-label="Действия с задачей"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg></button>`;el.querySelector('.task-name').append(document.createTextNode(t.title));el.querySelector('.check').onclick=()=>{if(t.completed){t.completed=false;t.completedAt=null;saveAndRender();toast('Задача возвращена')}else completeTask(t)};el.querySelector('.task-open').onclick=()=>openTaskAction(t);el.querySelector('.edit').onclick=()=>openTaskAction(t);return el}
$('#taskActionStart').onclick=()=>{const task=state.tasks.find(item=>item.id===taskActionId);$('#taskActionDialog').close();if(!task)return;if(task.completed){task.completed=false;task.completedAt=null;saveAndRender();toast('Задача возвращена')}else startLinkedTask(task)};
/* Cloud sync adapter: every user mutation is already saved locally before this hook runs. */
function refreshDesktopContext(){
  const profileName=state.profile?.name?.trim()||'SEVER';
  const profile=$('#localProfileName');if(profile)profile.textContent=profileName;
  const month=$('#desktopMonthTitle'),calendar=$('#desktopCalendar');
  if(month&&calendar){const year=dashboardCursor.getFullYear(),monthIndex=dashboardCursor.getMonth(),first=new Date(year,monthIndex,1),offset=(first.getDay()+6)%7;month.textContent=`${months[monthIndex]} ${year}`;calendar.innerHTML='';for(let index=0;index<42;index++){const date=new Date(year,monthIndex,index-offset+1),key=dayISO(date),items=state.tasks.filter(task=>task.date===key),button=document.createElement('button');button.type='button';button.className=(date.getMonth()===monthIndex?'':'dim ')+(key===TODAY?'today ':'')+(items.some(task=>task.completed)?'done ':'');button.textContent=date.getDate();button.title=items.length?`${pretty(key,false)}: ${items.length} задач` : pretty(key,false);button.onclick=()=>openDay(key);calendar.appendChild(button)}}
  const habits=$('#desktopHabitSummary');if(habits){habits.innerHTML='';const visible=state.habits.slice(0,4),weekStart=habitWeekStart();if(!visible.length)habits.innerHTML='<p>Добавьте привычку, чтобы видеть ритм дня.</p>';visible.forEach(habit=>{const row=document.createElement('section');row.className='habit-week-row';const title=document.createElement('button');title.type='button';title.className='habit-week-title';title.textContent=habit.title;title.setAttribute('aria-label',`Открыть привычку «${habit.title}»`);title.onclick=()=>switchView('habits');const markers=document.createElement('div');markers.className='habit-week-markers';habitWeekLabels.forEach((label,index)=>{const date=addDays(weekStart,index),complete=Boolean(state.checks[habit.id]?.includes(date)),future=date>TODAY,marker=document.createElement('button');marker.type='button';marker.className=`habit-day${complete?' done':''}${date===TODAY?' today':''}`;marker.dataset.day=label;marker.disabled=future;marker.setAttribute('aria-pressed',String(complete));marker.setAttribute('aria-label',`${habit.title}: ${label}, ${pretty(date,false)} — ${future?'будущий день':complete?'выполнено':'не отмечено'}`);marker.title=future?`${pretty(date,false)} · будущий день`:`${pretty(date,false)} · ${complete?'снять отметку':'отметить'}`;marker.textContent=complete?'✓':'';if(!future)marker.onclick=()=>toggleHabitCheck(habit.id,date);markers.appendChild(marker)});row.append(title,markers);habits.appendChild(row)})}
  const goal=$('#desktopGoalCard'),goalTitle=$('#desktopGoalTitle');if(goal&&goalTitle){const challenge=state.tasks.filter(task=>task.challenge);goal.classList.toggle('hidden',!challenge.length);if(challenge.length){const completed=challenge.filter(task=>task.completed).length,percent=Math.round(completed/challenge.length*100);goalTitle.textContent=state.challengeName||challenge[0].category;$('#desktopGoalProgress').style.width=`${percent}%`;$('#desktopGoalMeta').textContent=`${completed} из ${challenge.length} шагов · ${percent}%`}}
}
const appRender=render;
render=function(){appRender();refreshDesktopContext()};
function switchStorageScope(userId,localFallback=null){
  window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason:'account-change'}}));
  const nextKey=userId?`sever-cloud-state-v1:${userId}`:ANONYMOUS_KEY;
  const existing=userId?localStorage.getItem(nextKey):null;
  storageKey=nextKey;
  state=existing?readState(storageKey):migrate(localFallback||freshState());

  activeTaskId='';localStorage.removeItem('sever-active-task');
  return state;
}
function updateCloudStatus(status,user=null){
  const label=$('#cloudStatus'),settingsLabel=$('#cloudStatusSettings'),email=$('#accountEmail'),button=$('#localProfileBtn');
  const messages={local:'Локально',offline:'Офлайн · изменения сохраняются',pending:'Ожидает синхронизации',syncing:'Синхронизация…',synced:'✓ Синхронизировано','signed-out':'Войдите для синхронизации',migration:'Нужен выбор данных'};
  if(label)label.textContent=messages[status]||messages.local;if(settingsLabel)settingsLabel.textContent=messages[status]||messages.local;
  if(email)email.textContent=user?.email||'Данные только на этом устройстве';
  if(button)button.dataset.cloudStatus=status;
}
function openLocalProfile(){const dialog=$('#localProfileDialog');$('#localProfileInput').value=state.profile?.name||'';updateCloudStatus(window.SeverCloud?.status||'local',window.SeverCloud?.user);dialog.showModal()}
$('#localProfileBtn')?.addEventListener('click',openLocalProfile);
$('#localProfileForm')?.addEventListener('submit',event=>{event.preventDefault();state.profile={...(state.profile||{}),name:$('#localProfileInput').value.trim()};save();render();$('#localProfileDialog').close();toast('Профиль сохранён')});
$('#openLocalBackup')?.addEventListener('click',()=>{$('#localProfileDialog').close();$('#moreDialog').showModal()});
$$('.side-nav button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
$$('[data-quick-action]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.quickAction;if(action==='task')openTask();else if(action==='note'){switchView('notes');openNote()}else{switchView('timer');startTimer()}}));
$('#desktopOpenCalendar')?.addEventListener('click',()=>switchView('calendar'));$('#desktopOpenHabits')?.addEventListener('click',()=>switchView('habits'));$('#desktopOpenProgress')?.addEventListener('click',()=>switchView('progress'));
$('#desktopPrevMonth')?.addEventListener('click',()=>{dashboardCursor=new Date(dashboardCursor.getFullYear(),dashboardCursor.getMonth()-1,1);refreshDesktopContext()});$('#desktopNextMonth')?.addEventListener('click',()=>{dashboardCursor=new Date(dashboardCursor.getFullYear(),dashboardCursor.getMonth()+1,1);refreshDesktopContext()});
const baseSwitchView=switchView;
switchView=function(name){baseSwitchView(name);$$('.app-nav button').forEach(button=>{const active=button.dataset.view===name;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')})};
let focusStartedAt=0;
const baseStartTimer=startTimer;
startTimer=function(){if(!timerRunning)focusStartedAt=Date.now();return baseStartTimer()};
const baseTimerTick=timerTick;
timerTick=function(){const linkedTaskId=activeTaskId,finished=timerRunning&&timerEnd>0&&Date.now()>=timerEnd;baseTimerTick();if(finished){state.focusSessions??=[];state.focusSessions.push({id:uid(),taskId:linkedTaskId||null,durationMinutes:timerMinutes,startedAt:focusStartedAt||Date.now()-timerMinutes*60000,completedAt:Date.now(),status:'completed',createdAt:Date.now(),updatedAt:Date.now()});focusStartedAt=0;save();renderProgress()}};
window.SeverApp={
  getState:()=>state,
  freshState:()=>migrate(freshState()),
  replaceState:async next=>{window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason:'cloud-replace'}}));state=migrate(next);await persistLocal();render();renderSuggestions()},
  exportProtectedVault,
  persist:()=>persistLocal(),
  switchStorageScope,
  getLegacyStateFor:userId=>{const owner=localStorage.getItem(LEGACY_OWNER_KEY);if(owner&&owner!==userId)return freshState();localStorage.setItem(LEGACY_OWNER_KEY,userId);return readState(KEY)},
  render:()=>{render();renderSuggestions()},
  setCloudStatus:updateCloudStatus,
  resetPlanner,
  switchView,
  startGuide,
  lockProtectedNotes:reason=>window.dispatchEvent(new CustomEvent('sever:lock-protected-notes',{detail:{reason}})),
  onLocalSave:null
};
