const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='sever-data-v1',months=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const dayISO=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateOf=s=>new Date(s+'T12:00:00');
const addDays=(s,n)=>{const d=dateOf(s);d.setDate(d.getDate()+n);return dayISO(d)};
const TODAY=dayISO();let cursor=new Date(),deferredInstall=null;
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);

function freshState(){return{version:2,onboarded:false,challengeStart:TODAY,challengeDays:30,challengeName:'',tasks:[],habits:[],checks:{}}}
function migrate(data){if(!data?.tasks)return freshState();data.habits??=[];data.checks??={};data.challengeStart??=TODAY;const challenge=data.tasks.filter(t=>t.challenge);data.challengeDays??=(new Set(challenge.map(t=>t.date)).size||30);data.challengeName??=[...new Set(challenge.map(t=>t.category))].join(' + ');data.onboarded??=true;data.version=2;return data}
function readState(){try{const raw=localStorage.getItem(KEY);return raw?migrate(JSON.parse(raw)):freshState()}catch{return freshState()}}
let state=readState();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function pretty(s,weekday=true){return dateOf(s).toLocaleDateString('ru-RU',weekday?{weekday:'long',day:'numeric',month:'long'}:{day:'numeric',month:'long'})}
function empty(text){return `<div class="empty">${text}</div>`}
function rollover(){let moved=0;state.tasks.forEach(t=>{if(!t.challenge&&!t.completed&&t.date<TODAY){t.date=TODAY;moved++}});if(moved){save();setTimeout(()=>toast(`Перенесено на сегодня: ${moved}`),300)}}

function taskElement(t){const el=document.createElement('article');el.className='task '+(t.completed?'done':'');el.innerHTML=`<button class="check">${t.completed?'✓':''}</button><div><div class="task-name">${t.priority?'<span class="star">★</span>':''}</div><div class="task-meta">${t.duration} мин · ${escapeText(t.category)}</div></div><button class="edit">•••</button>`;el.querySelector('.task-name').append(document.createTextNode(t.title));el.querySelector('.check').onclick=()=>{t.completed=!t.completed;save();render();if(t.completed)toast('Шаг выполнен')};el.querySelector('.edit').onclick=()=>openTask(t);return el}
function fillTasks(root,list,text){const box=$(root);box.innerHTML='';if(!list.length){box.innerHTML=empty(text);return}list.sort((a,b)=>Number(b.priority)-Number(a.priority)).forEach(t=>box.appendChild(taskElement(t)))}
function challengeTasks(category){return state.tasks.filter(t=>t.challenge&&t.category===category)}
function challengeCategories(){return[...new Set(state.tasks.filter(t=>t.challenge).map(t=>t.category))]}
function renderChallenge(){const categories=challengeCategories(),block=$('#challengeBlock');block.classList.toggle('hidden',!categories.length);if(!categories.length)return;const days=state.challengeDays||30;$('#challengeTitle').textContent=state.challengeName||categories.join(' + ');const elapsed=Math.floor((dateOf(TODAY)-dateOf(state.challengeStart))/86400000)+1;$('#dayCounter').textContent=`День ${Math.min(days,Math.max(1,elapsed))}/${days}`;const root=$('#challengeProgress');root.innerHTML='';categories.forEach(category=>{const list=challengeTasks(category),done=list.filter(t=>t.completed).length,card=document.createElement('article');card.innerHTML=`<div><span></span><b>${done}/${list.length}</b></div><i><em style="width:${list.length?done/list.length*100:0}%"></em></i>`;card.querySelector('span').textContent=category;root.appendChild(card)})}

function renderToday(){const items=state.tasks.filter(t=>t.date===TODAY);fillTasks('#todayTasks',items,'Сегодня всё свободно. Добавь небольшой шаг.');$('#todayLoad').textContent=items.filter(t=>!t.completed).reduce((a,t)=>a+t.duration,0)+' мин';$('#todayLabel').textContent=pretty(TODAY).toUpperCase();renderChallenge();const tracked=items.some(t=>t.challenge)?items.filter(t=>t.challenge):items,done=tracked.filter(t=>t.completed).length,percent=tracked.length?Math.round(done/tracked.length*100):0;$('#coursePercent').textContent=percent+'%';$('#courseArc').style.strokeDashoffset=264*(1-percent/100);const next=items.find(t=>!t.completed&&t.challenge)||items.find(t=>!t.completed&&t.priority)||items.find(t=>!t.completed);if(next){$('#courseTitle').textContent=next.challenge?'Держи курс':'Следующий ориентир';$('#courseText').textContent=`Сейчас лучше начать: ${next.title.toLowerCase()} — ${next.duration} минут.`;$('#courseAction').textContent='Показать задачу';$('#courseAction').onclick=()=>$('#todayTasks').scrollIntoView({behavior:'smooth'})}else if(items.length){$('#courseTitle').textContent='Курс выдержан';$('#courseText').textContent='Все задачи на сегодня выполнены. Отдых тоже часть движения.';$('#courseAction').textContent='Посмотреть прогресс';$('#courseAction').onclick=()=>switchView('progress')}else{$('#courseTitle').textContent='Наметь ориентир';$('#courseText').textContent='Добавь первый небольшой шаг на сегодня.';$('#courseAction').textContent='Добавить задачу';$('#courseAction').onclick=()=>openTask()}}

function renderCalendar(){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7;$('#monthTitle').textContent=`${months[m]} ${y}`;const root=$('#calendar');root.innerHTML='';for(let i=0;i<42;i++){const d=new Date(y,m,i-offset+1),key=dayISO(d),items=state.tasks.filter(t=>t.date===key),b=document.createElement('button');b.className='day'+(d.getMonth()!==m?' dim':'')+(key===TODAY?' today':'');b.innerHTML=`<span>${d.getDate()}</span>${items.slice(0,3).map(t=>`<u>${t.completed?'✓ ':''}${escapeText(t.title)}</u>`).join('')}`;b.onclick=()=>openTask(null,key);root.appendChild(b)}}
function streak(){let n=0,d=TODAY;const hasChallenge=state.tasks.some(t=>t.challenge);while(true){const list=state.tasks.filter(t=>t.date===d&&(!hasChallenge||t.challenge));if(!list.length||!list.every(t=>t.completed))break;n++;d=addDays(d,-1)}return n}
function renderProgress(){const completed=state.tasks.filter(t=>t.completed);$('#allDone').textContent=completed.length;$('#streak').textContent=streak()+' дней';$('#focusMinutes').textContent=completed.reduce((a,t)=>a+t.duration,0)+' мин';const root=$('#heatmap'),hasChallenge=state.tasks.some(t=>t.challenge),span=Math.min(hasChallenge?(state.challengeDays||30):30,60),start=hasChallenge?state.challengeStart:addDays(TODAY,-29);root.innerHTML='';for(let i=0;i<span;i++){const date=addDays(start,i),list=state.tasks.filter(t=>t.date===date&&(!hasChallenge||t.challenge)),done=list.filter(t=>t.completed).length,el=document.createElement('div');el.className='heat '+(list.length&&done===list.length?'full':done?'half':'');el.title=`${pretty(date,false)}: ${done}/${list.length}`;el.textContent=i+1;root.appendChild(el)}const from=addDays(TODAY,-6),week=state.tasks.filter(t=>t.date>=from&&t.date<=TODAY),done=week.filter(t=>t.completed).length,total=week.length,p=total?Math.round(done/total*100):0;$('#reviewTitle').textContent=`${done} из ${total} задач · ${p}%`;$('#reviewText').textContent=p>=80?'Ты уверенно держишь курс. Сохраняй такой темп.':p>=50?'Хорошее движение. На следующей неделе выбери три главных шага заранее.':'Сделай план легче: оставь одну небольшую обязательную задачу на день.'}
function renderHabits(){const root=$('#habitList');root.innerHTML='';if(!state.habits.length){root.innerHTML=empty('Добавь привычку, которую хочешь повторять каждый день.');return}state.habits.forEach(h=>{const done=state.checks[h.id]?.includes(TODAY),el=document.createElement('article');el.className='habit '+(done?'done':'');el.innerHTML=`<h3></h3><p>Сегодня · ${done?'выполнено':'ещё не отмечено'}</p><button>${done?'✓ Выполнено':'Отметить сегодня'}</button>`;el.querySelector('h3').textContent=h.title;el.querySelector('button').onclick=()=>{const dates=state.checks[h.id]??=[];state.checks[h.id]=done?dates.filter(x=>x!==TODAY):[...dates,TODAY];save();renderHabits();toast(done?'Отметка снята':'Привычка выполнена')};root.appendChild(el)})}
function render(){renderToday();renderCalendar();renderProgress();renderHabits()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='calendar')renderCalendar()}
function escapeText(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}

function openTask(task=null,date=TODAY){$('#taskDialogTitle').textContent=task?'Изменить задачу':'Новая задача';$('#taskId').value=task?.id||'';$('#taskTitle').value=task?.title||'';$('#taskDate').value=task?.date||date;$('#taskDuration').value=task?.duration||30;$('#taskCategory').value=['Личное','Учёба','Работа','Другое'].includes(task?.category)?task.category:'Учёба';$('#taskPriority').checked=Boolean(task?.priority);$('#deleteTask').classList.toggle('hidden',!task);$('#taskDialog').showModal()}
function parseQuick(text){let date=TODAY;if(/завтра/i.test(text))date=addDays(TODAY,1);const duration=+(text.match(/(\d{1,3})\s*(?:мин|минут)/i)?.[1]||30);let title=text.replace(/^(добавь|запиши|создай)\s*/i,'').replace(/\b(сегодня|завтра)\b/ig,'').replace(/\d{1,3}\s*(?:мин|минут)/ig,'').replace(/\s+/g,' ').trim();const category=/python|пайтон/i.test(title)?'Учёба':/пдд/i.test(title)?'Учёба':'Личное';return{title:title||text,date,duration,category,challenge:false,completed:false,priority:false,id:uid()}}

$('#quickForm').onsubmit=e=>{e.preventDefault();const text=$('#quickInput').value.trim();if(!text)return;state.tasks.push(parseQuick(text));save();$('#quickInput').value='';render();toast('Добавлено')};$('#openAdd').onclick=()=>openTask();$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#taskForm').onsubmit=e=>{e.preventDefault();const id=$('#taskId').value,existing=state.tasks.find(t=>t.id===id),data={title:$('#taskTitle').value.trim(),date:$('#taskDate').value,duration:Math.max(1,+$('#taskDuration').value||30),category:$('#taskCategory').value,priority:$('#taskPriority').checked};if(existing)Object.assign(existing,data);else state.tasks.push({id:uid(),...data,challenge:false,completed:false});save();$('#taskDialog').close();render();toast('Сохранено')};$('#deleteTask').onclick=()=>{const id=$('#taskId').value;state.tasks=state.tasks.filter(t=>t.id!==id);save();$('#taskDialog').close();render();toast('Удалено')};
$('#openHabit').onclick=()=>$('#habitDialog').showModal();$('#habitForm').onsubmit=e=>{e.preventDefault();const id=uid();state.habits.push({id,title:$('#habitTitle').value.trim()});state.checks[id]=[];save();$('#habitTitle').value='';$('#habitDialog').close();renderHabits();toast('Привычка добавлена')};$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#prevMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('sever-theme',theme);$('#themeBtn').textContent=theme==='dark'?'☀':'☾';document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#050505':'#f5f5f5'}$('#themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');applyTheme(document.documentElement.dataset.theme);
$('#moreBtn').onclick=()=>$('#moreDialog').showModal();$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sever-backup-${TODAY}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.tasks))throw 0;state=migrate(data);save();render();$('#moreDialog').close();toast('Данные восстановлены')}catch{toast('Неверный файл копии')}};$('#resetBtn').onclick=()=>{if(confirm('Удалить все данные и настроить SEVER заново?')){state=freshState();save();render();$('#moreDialog').close();$('#welcomeDialog').showModal()}};
function beginCourse(goals,days,minutes){const tasks=[];for(let i=0;i<days;i++)goals.forEach(goal=>tasks.push({id:uid(),title:goal,date:addDays(TODAY,i),duration:minutes,category:goal,challenge:true,completed:false,priority:true}));state={version:2,onboarded:true,challengeStart:TODAY,challengeDays:days,challengeName:goals.join(' + '),tasks,habits:[],checks:{}};save();render();$('#welcomeDialog').close();toast('Личный курс создан')}
$('#welcomeForm').onsubmit=e=>{e.preventDefault();const goals=[$('#goalOne').value.trim(),$('#goalTwo').value.trim()].filter(Boolean),days=Math.max(7,Math.min(365,+$('#challengeDays').value||30)),minutes=Math.max(5,Math.min(600,+$('#challengeMinutes').value||30));beginCourse(goals,days,minutes)};$('#startEmpty').onclick=()=>{state.onboarded=true;save();render();$('#welcomeDialog').close();toast('Чистый планер готов')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
rollover();save();render();if(!state.onboarded)$('#welcomeDialog').showModal();
