import webpush from 'npm:web-push@3.6.7';
import { createClient } from 'npm:@supabase/supabase-js@2.57.4';

type PushJob={delivery_id:number;subscription_id:string;endpoint:string;p256dh:string;auth:string;task_id:string;user_id:string;task_title:string;scheduled_for:string;scheduled_time:string;reminder_kind:'day_before'|'fifteen_minutes';due_at:string};
type PushGroup={key:string;jobs:PushJob[]};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function safeEqual(left:string,right:string){const a=new TextEncoder().encode(left),b=new TextEncoder().encode(right);if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i+=1)diff|=a[i]^b[i];return diff===0;}
const timeLabel=(value:string)=>typeof value==='string'?value.slice(0,5):'';
function groupJobs(jobs:PushJob[]):PushGroup[]{const groups=new Map<string,PushJob[]>();for(const job of jobs){const dueMinute=String(job.due_at||'').slice(0,16),key=`${job.subscription_id}:${job.reminder_kind}:${dueMinute}`,group=groups.get(key)||[];group.push(job);groups.set(key,group);}return[...groups.entries()].map(([key,grouped])=>({key,jobs:grouped}));}
function payloadFor(group:PushGroup){const jobs=group.jobs,first=jobs[0],soon=first.reminder_kind==='fifteen_minutes';if(jobs.length===1){const time=timeLabel(first.scheduled_time);return{title:soon?`Через 15 минут · ${first.task_title}`:`Завтра · ${first.task_title}`,body:soon?`${time} · Скоро начало задачи.`:`${time} · Напоминание за 1 день.`,tag:`sever-task-${first.task_id}-${first.reminder_kind}-${first.due_at}`,url:`./?view=today&task=${encodeURIComponent(first.task_id)}`,taskId:first.task_id,reminderKind:first.reminder_kind};}const names=jobs.slice(0,2).map(job=>job.task_title).join(', '),rest=Math.max(0,jobs.length-2);return{title:soon?`Через 15 минут · ${jobs.length} задачи`:`Завтра · ${jobs.length} задачи`,body:`${names}${rest?` и ещё ${rest}`:''}.`,tag:`sever-bundle-${first.subscription_id}-${first.reminder_kind}-${String(first.due_at).slice(0,16)}`,url:'./?view=today',reminderKind:first.reminder_kind,count:jobs.length};}
export default{async fetch(req:Request):Promise<Response>{if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const supabaseUrl=Deno.env.get('SUPABASE_URL')||'',serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!supabaseUrl||!serviceRoleKey)return json({error:'SERVER_CONFIG'},503);const admin=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});const secretsResult=await admin.rpc('sever_push_runtime_secrets').single();if(secretsResult.error||!secretsResult.data)return json({error:'PUSH_CONFIG'},503);const secrets=secretsResult.data as{vapid_public:string;vapid_private:string;cron_token:string},presented=req.headers.get('x-sever-cron-token')||'';if(!presented||!safeEqual(presented,secrets.cron_token||''))return json({error:'UNAUTHORIZED'},401);if(!secrets.vapid_public||!secrets.vapid_private)return json({error:'PUSH_CONFIG'},503);webpush.setVapidDetails('https://golovalisaia-hub.github.io/sever-planner/',secrets.vapid_public,secrets.vapid_private);const claimed=await admin.rpc('sever_claim_due_pushes',{p_limit:120});if(claimed.error)return json({error:'CLAIM_FAILED'},503);const jobs=(claimed.data||[]) as PushJob[],groups=groupJobs(jobs);let sent=0,failed=0,retired=0;for(const group of groups){const first=group.jobs[0];try{await webpush.sendNotification({endpoint:first.endpoint,keys:{p256dh:first.p256dh,auth:first.auth}},JSON.stringify(payloadFor(group)),{TTL:first.reminder_kind==='day_before'?43200:1800,urgency:first.reminder_kind==='fifteen_minutes'?'high':'normal'});const ids=group.jobs.map(job=>job.delivery_id);await admin.from('push_deliveries').update({status:'sent',sent_at:new Date().toISOString(),error_code:null}).in('id',ids);sent+=group.jobs.length;}catch(error:any){const statusCode=Number(error?.statusCode||error?.status||0),code=statusCode?`HTTP_${statusCode}`:'SEND_FAILED',ids=group.jobs.map(job=>job.delivery_id);await admin.from('push_deliveries').update({status:'failed',error_code:code}).in('id',ids);if(statusCode===404||statusCode===410){await admin.from('push_subscriptions').update({enabled:false,updated_at:new Date().toISOString()}).eq('id',first.subscription_id);retired+=1;}failed+=group.jobs.length;}}return json({ok:true,claimed:jobs.length,groups:groups.length,sent,failed,retired});}};
